/*
 * File: app/view/ktsp/ktspZJView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ktsp.ktspZJView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ktspZJView',

    layout: {
        type: 'border'
    },
    title: '课题审批-专家',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [{
		                xtype: 'ktgrid',
		                id:'ktsp_ZJ_grid',
                        flag:'zj',
		                region: 'center',
		                tbar2:[{
		                    	xtype: 'tbseparator'
		                	},{
				                id:'ktsp_zj_html_view',
				                text:'阅读模式',
				                iconCls:'icon-view',
				                action:'ktsp_zj_html_view_act'
				            },{
		                    	xtype: 'tbseparator'
		                	},{
			                    xtype: 'button',
			                    id:'ktsp_zj_lsyj',
			                    iconCls: 'icon-comments',
			                    action:'ktsp_zj_lsyj_act',
			                    text: '历史意见'
			                }
			            ]
		            },
                {
	            	xtype: 'panel',
	                region: 'south',
	                height: 320,
                    id: 'normalpanel',
                    layout: {
                        type: 'fit'
                    },
                    title: '',
                    items: [
	                    {	// 网评-专家
	                        xtype: 'panel',
	                        autoScroll: true,
	                        id: 'wpZjPanel',
	                        border:0,
	                        hidden:true,
	                        layout: {
	                            type: 'fit'
	                        },
	                        title: '',
	                        items: [{ 
									xtype: 'form',
									id: 'wpZjForm',
									border:0,
									dockedItems: [
										            {
			                                    xtype: 'toolbar',
			                                    dock: 'bottom',
			                                    rtl: true,
			                                    items: [
			                                        {
			        					            	xtype: 'tbseparator'
			        					        	},{
			                                            xtype: 'button',
			                                            iconCls: 'icon-temp-save',
			                                            action:'ktsp_save_specialist_opinion_act',
			                                            text: '保存草稿'
			                                        },{
			                                        	xtype: 'tbseparator'
			                                    	},
			                                        {
			                                            xtype: 'button',
			                                            iconCls: 'icon-submit',
			                                            action:'ktsp_submit_specialist_opinion_act',
			                                            text: '发布意见'
			                                        }
			                                    ]
			                                },
			                                {
			                                    xtype: 'radiogroup',
			                                    dock: 'bottom',
			                                    labelWidth: 100,
			                                    padding: '0 500 0 10',
			                                    id:'issueWpLast',
			                                    name:'issueWpLast',
			                                    fieldLabel: '审查结论总意见',
			                                    items: [
			                                        {
			                                            xtype: 'radiofield',
			                                            name:'issueWpLast',
			                                            inputValue: '0',
			                                            checked: true,
			                                            boxLabel: '修改后签订合同'
			                                        },
			                                        {
			                                            xtype: 'radiofield',
			                                            name:'issueWpLast',
			                                            inputValue: '1',
			                                            boxLabel: '同意签订合同'
			                                        },
			                                        {
			                                            xtype: 'radiofield',
			                                            name:'issueWpLast',
			                                            inputValue: '2',
			                                            boxLabel: '不同意签订合同'
			                                        }
			                                    ]
			                                }
			                            ],
	                            items: [
	                                {
	                                    xtype: 'tabpanel',
	                                    activeTab: 0,
	                                    border:0,
	                                    items: [
	                                        {
	                                            xtype: 'panel',
	                                            title: '研究目标',
	                                            layout: {
	                                            	type: 'absolute'
	                                            },
	                                            items: [
	                                                    {
	                                                        xtype: 'htmleditor',
	                                                        id:'issueWpYjmb',
	                                                        name:'issueWpYjmb',
	                                                        height: 300,
	                                                        value:''
	                                                    }
	                                                ]
	                                        },
	                                        {
	                                            xtype: 'panel',
	                                            title: '研究内容与任务分解',
	                                            layout: {
	                                            	type: 'absolute'
	                                            },
	                                            items: [
	                                                    {
	                                                        xtype: 'htmleditor',
	                                                        id:'issueWpYjnrRwfj',
	                                                        name:'issueWpYjnrRwfj',
	                                                        height: 300,
	                                                        value:''
	                                                    }
	                                                ]
	                                        },
	                                        {
	                                            xtype: 'panel',
	                                            title: '预期成果与考核指标',
	                                            layout: {
	                                            	type: 'absolute'
	                                            },
	                                            items: [
	                                                    {
	                                                        xtype: 'htmleditor',
	                                                        height: 300,
	                                                        id:'issueWpYqcgKhzb',
	                                                        name:'issueWpYqcgKhzb',
	                                                        value:''
	                                                    }
	                                                ]
	                                        },
	                                        {
	                                            xtype: 'panel',
	                                            title: '合作单位与任务分工',
	                                            layout: {
	                                            	type: 'absolute'
	                                            },
	                                            items: [
	                                                    {
	                                                        xtype: 'htmleditor',
	                                                        height: 300,
	                                                        id:'issueWpHzdwRwfg',
	                                                        name:'issueWpHzdwRwfg',
	                                                        value:''
	                                                    }
	                                                ]
	                                        }
	                                    ]
	                                }
	                            ]
		                        }
	                        ]
	                    },{
    		                xtype: 'textfield',
    		                id:'id',
    		                name:'id',
    		                value:'',
    		                hidden:true
    		            },{
    		                xtype: 'textfield',
    		                id:'issueId',
    		                name:'issueId',
    		                value:'',
    		                hidden:true
    		            },{
    		                xtype: 'textfield',
    		                id:'peopleId',
    		                name:'peopleId',
    		                value:'',
    		                hidden:true
    		            },{
    		                xtype: 'textfield',
    		                id:'createTime',
    		                name:'createTime',
    		                value:'',
    		                hidden:true
    		            }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});