/*
 * File: app/view/ktsp/ktspView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ktsp.ktspView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ktspView',

    layout: {
        type: 'border'
    },
    title: '课题审批',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [{
		                xtype: 'ktgrid',
		                id:'ktsp_grid',
		                region: 'center',
		                tbar2:[/*{
		                    	xtype: 'tbseparator'
		                	},{
                                text:'新建课题授权',
                                iconCls:'icon-add',
                                action:'ktsp_kt_add_act'
                            },*/{
                                xtype: 'tbseparator',
                                id:'html_view_separator',
                                hidden:true
                            },{
				                id:'ktsp_html_but',
				                text:'阅读模式',
				                iconCls:'icon-view',
				                action:'ktsp_html_view_act',
				                hidden:true
				            },
			                {
			                    xtype: 'tbseparator',
			                    id:'xssc_separator',
			                    hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_xssc_but',
			                    iconCls: 'icon-flag-pink',
			                    action:'ktsp_xssc_act',
			                    text: '启动形式审查',
				                hidden:true
			                },
			                {
			                    xtype: 'tbseparator',
			                    id:'zdjz_separator',
			                    hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_zdzj_but',
			                    iconCls: 'icon-user-add',
			                    action:'ktsp_zdzj_act',
			                    text: '指定专家',
				                hidden:true
			                },
			                {
			                    xtype: 'tbseparator',
			                    id:'other_separator',
			                    hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_start_hyps_but',
			                    iconCls: 'icon-flag-green',
			                    action:'ktsp_start_hyps_act',
			                    text: '启动会议评审',
				                hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_start_fs_but',
			                    iconCls: 'icon-flag-yellow',
			                    action:'ktsp_start_fs_act',
			                    text: '启动复审',
				                hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_complete_fs_but',
			                    iconCls: 'icon-flag-yellow',
			                    action:'ktsp_complete_fs_act',
			                    text: '复审通过',
				                hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_qdht',
			                    iconCls: 'icon-flag-yellow',
			                    action:'ktsp_complete_act',
			                    text: '合同签订',
				                hidden:true
			                },
			                {
			                    xtype: 'tbseparator',
			                    id:'ckxgls_separator',
			                    hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_ckxgls',
			                    iconCls: 'icon-modify-history',
			                    action:'ktsp_ckxgls_act',
			                    text: '查看修改历史',
				                hidden:true
			                },
			                {
			                    xtype: 'tbseparator',
			                    id:'lsyj_separator',
			                    hidden:true
			                },
			                {
			                    xtype: 'button',
			                    id:'ktsp_lsyj',
			                    iconCls: 'icon-comments',
			                    action:'ktsp_lsyj_act',
			                    text: '历史意见',
				                hidden:true
			                }
//			                ,
//			                {
//			                    xtype: 'tbseparator',
//			                },
//			                {
//			                    xtype: 'button',
//			                    id:'ktsp_test',
//			                    iconCls: 'icon-comments',
//			                    action:'ktsp_test_act',
//			                    text: '测试'
//			                }
			            ]
		            },
                {
	            	xtype: 'panel',
	                region: 'south',
	                height: 320,
                    id: 'normalpanel',
                    layout: {
                        type: 'fit'
                    },
                    title: '',
                    items: [
                          {   // 空白
	                        xtype: 'panel',
	                        id: 'blankPanel',
	                        border:0,
	                        autoScroll: true,
	                        layout: {
	                            type: 'fit'
	                        },
	                        title: '',
	                        items: [
								{ 
									xtype: 'panel',
                                    title: '意见区',
                                    border:0,
                                    layout: {
                                    	type: 'anchor'
                                    }
								}
		                    ]
	                    },{ // 形式审查&修改
                        	xtype: 'panel',
	                        autoScroll: true,
	                        id: 'xsPanel',
	                        hidden: true,
	                        border:0,
	                        layout: {
	                            type: 'fit'
	                        },
	                        title: '',
	                        items: [
									{ 	xtype: 'form',
										id: 'xsForm',
										border:0,
	                                    items: [
		                                       {
		                                        xtype: 'tabpanel',
		                                        id: 'xstabpanel',
		                                        activeTab: 0,
		                                        border:0,
		                                        items: [
		                                                {
		                                                    xtype: 'panel',
		                                                    title: '基本信息的审查结果',
		                                                    layout: {
		                                                    	type: 'absolute'
		                                                    },
		                                                    items: [
		                                                            {
		                                                                xtype: 'htmleditor',
		                                                                name:'issueXsJbxx',
		                                                                id:'issueXsJbxx',
		                                                                height: 300,
		                                                                fieldLabel: ''
		                                                            }
		                                                        ]
		                                                },
		                                                {
		                                                    xtype: 'panel',
		                                                    title: '参与单位及人员的审查结果',
		                                                    layout: {
		                                                    	type: 'absolute'
		                                                    },
		                                                    items: [
		                                                            {
		                                                                xtype: 'htmleditor',
		                                                                name:'issueXsCydwRy',
		                                                                id:'issueXsCydwRy',
		                                                                height: 300,
		                                                                fieldLabel: ''
		                                                            }
		                                                        ]
		                                                },
		                                                {
		                                                    xtype: 'panel',
		                                                    title: '经费的审查结果',
		                                                    layout: {
		                                                    	type: 'absolute'
		                                                    },
		                                                    items: [
		                                                            {
		                                                                xtype: 'htmleditor',
		                                                                name:'issueXsJfsc',
		                                                                id:'issueXsJfsc',
		                                                                height: 300,
		                                                                fieldLabel: ''
		                                                            }
		                                                        ]
		                                                },
		                                                {
		                                                    xtype: 'panel',
		                                                    title: '任务内容、考核指标审查结果',
		                                                    layout: {
		                                                    	type: 'absolute'
		                                                    },
		                                                    items: [
		                                                            {
		                                                                xtype: 'htmleditor',
		                                                                name:'issueXsRwnrKhzb',
		                                                                id:'issueXsRwnrKhzb',
		                                                                height: 300,
		                                                                fieldLabel: ''
		                                                            }
		                                                        ]
		                                                },
		                                                {
		                                                    xtype: 'panel',
		                                                    title: '存在其他问题',
		                                                    layout: {
		                                                    	type: 'absolute'
		                                                    },
		                                                    items: [
		                                                            {
		                                                                xtype: 'htmleditor',
		                                                                id:'issueXsQt',
		                                                                name:'issueXsQt',
		                                                                height: 300,
		                                                                fieldLabel: ''
		                                                            }
		                                                        ]
		                                                }
		                                            ]
		                                       }
			                            ],
			                            dockedItems: [{
											xtype: 'toolbar',
											id:'ktsp_xssc_save_submit',
											dock: 'bottom',
											items: [
												{
													xtype: 'tbseparator'
												},{
												    xtype: 'button',
												    iconCls: 'icon-temp-save',
												    action:'ktsp_xssc_save_opinion_act',
												    text: '保存草稿'
												},{
													xtype: 'tbseparator'
												},
												{
												    xtype: 'button',
												    iconCls: 'icon-submit',
												    action:'ktsp_xssc_submit_opinion_act',
												    text: '发布意见'
												}
											]
										}
                                    ]
                                    }
                                ]
	                    },
	                    {	// 网评-水办
	                        xtype: 'panel',
	                        id: 'wpSbPanel',
	                        border:0,
	                        autoScroll: true,
	                        layout: {
	                            type: 'fit'
	                        },
	                        hidden: true,
	                        title: '',
	                        items: [{ 
									xtype: 'form',
									id: 'wpSbForm',
									border:0,
				                    layout: {
				                        type: 'fit'
				                    },
				                    title: '',
				                    items: [
				                            {
				                                xtype: 'tabpanel',
				                                border:0,
				                                activeTab: 0,
				                                items: [
				                                    {
				                                        xtype: 'panel',
				                                        title: '意见汇总',
				                                        layout: {
				                                        	type: 'absolute'
				                                        },
				                                        dockedItems: [
				                                                        {
				                                                            xtype: 'toolbar',
				                                                            dock: 'bottom',
				                                                            id:'ktsp_yjhz_save_submit',
				                                                            rtl: true,
				                                                            items: [
				                                                                {
				                                					            	xtype: 'tbseparator'
				                                					        	},{
				                                                                    xtype: 'button',
				                                                                    iconCls: 'icon-temp-save',
				                                                                    action:'ktsp_save_sb_opinion_act',
				                                                                    text: '保存草稿'
				                                                                },{
				                                                                	xtype: 'tbseparator'
				                                                            	},
				                                                                {
				                                                                    xtype: 'button',
				                                                                    iconCls: 'icon-submit',
				                                                                    action:'ktsp_submit_sb_opinion_act',
				                                                                    text: '发布意见'
				                                                                }
				                                                            ]
				                                                        }
				                                                    ],
				                                        items: [
																{
			                                                        xtype: 'htmleditor',
			                                                        id:'issueWpYjhz',
			                                                        name:'issueWpYjhz',
			                                                        height: 300,
			                                                        fieldLabel: ''
			                                                    }
				                                            ]
				                                    }
				                                ]
				                            }
				                        ]
				                }
	                        ]
	                    },
	                    {   // 会议审查
	                        xtype: 'panel',
	                        id: 'hyscPanel',
	                        border:0,
	                        autoScroll: true,
	                        layout: {
	                            type: 'fit'
	                        },
	                        hidden: true,
	                        title: '',
	                        items: [
								{ 
									xtype: 'form',
									id: 'hyscForm',
									border:0,
                                    items: [
                                          {
		                                    xtype: 'panel',
		                                    title: '编辑意见',
		                                    border:0,
		                                    layout: {
		                                    	type: 'absolute'
		                                    },
		                                    items: [
	    										{
	                                            xtype: 'htmleditor',
	                                            id:'issueHyscYj',
	                                            name:'issueHyscYj',
	                                            height: 300,
	                                            fieldLabel: ''
		                                        }
		                                    ]
	                                    }
	                                ],
	                                dockedItems: [
                                          {
                                             xtype: 'toolbar',
                                             border:0,
                                             dock: 'bottom',
                                             rtl: true,
                                             items: [
                                                 {
                 					            	xtype: 'tbseparator'
                 					        	},{
                                                     xtype: 'button',
                                                     iconCls: 'icon-temp-save',
                                                     action:'ktsp_hyps_save_opinion_act',
                                                     text: '保存草稿'
                                                 },{
                                                 	xtype: 'tbseparator'
                                             	},
                                                 {
                                                     xtype: 'button',
                                                     iconCls: 'icon-submit',
                                                     action:'ktsp_hyps_submit_opinion_act',
                                                     text: '发布意见'
                                                 }
                                             ]
                                        }
                                    ]
								}
		                    ]
	                    },
	                    {   // 复审
	                        xtype: 'panel',
	                        id: 'fsPanel',
	                        border:0,
	                        autoScroll: true,
	                        layout: {
	                            type: 'fit'
	                        },
	                        hidden: true,
	                        title: '',
	                        items: [{ 	
	                            	xtype: 'form',
	                            	id:'fsForm',
	                                border:0,
	                                dockedItems: [
	                                    {
	                                        xtype: 'toolbar',
	                                        dock: 'bottom',
	                                        rtl: true,
	                                        items: [
	                                            {
	            					            	xtype: 'tbseparator'
	            					        	},{
	                                                xtype: 'button',
	                                                iconCls: 'icon-temp-save',
	                                                action:'ktsp_fs_save_opinion_act',
	                                                text: '保存草稿'
	                                            },{
	                                            	xtype: 'tbseparator'
	                                        	},
	                                            {
	                                                xtype: 'button',
	                                                iconCls: 'icon-submit',
	                                                action:'ktsp_fs_submit_opinion_act',
	                                                text: '发布意见'
	                                            }
	                                        ]
	                                    }
	                                ],
	                                items: [
	                                    {
	                                        xtype: 'tabpanel',
	                                        activeTab: 0,
	                                        border:0,
	                                        items: [
	                                            {
	                                                xtype: 'panel',
	                                                title: '根据专家意见修改完善情况',
	                                                layout: {
	                                                	type: 'absolute'
	                                                },
	                                                items: [
	                                                        {
	                                                            xtype: 'htmleditor',
	                                                            id:'issueFsXgws',
	                                    		                name:'issueFsXgws',
	                                                            height: 300,
	                                                            fieldLabel: ''
	                                                        }
	                                                    ]
	                                            },
	                                            {
	                                                xtype: 'panel',
	                                                title: '复审意见',
	                                                layout: {
	                                                	type: 'absolute'
	                                                },
	                                                items: [
	                                                        {
	                                                            xtype: 'htmleditor',
	                                                            id:'issueFsFsyj',
	                                    		                name:'issueFsFsyj',
	                                                            height: 300,
	                                                            fieldLabel: ''
	                                                        }
	                                                ]
	                                            }
	                                        ]
	                                    }
	                                ]
	                            }
	                        ]
	                    },{
    		                xtype: 'textfield',
    		                id:'id',
    		                name:'id',
    		                value:'',
    		                hidden:true
    		            },{
    		                xtype: 'textfield',
    		                id:'issueId',
    		                name:'issueId',
    		                value:'',
    		                hidden:true
    		            },{
    		                xtype: 'textfield',
    		                id:'peopleId',
    		                name:'peopleId',
    		                value:'',
    		                hidden:true
    		            },{
    		                xtype: 'textfield',
    		                id:'createTime',
    		                name:'createTime',
    		                value:'',
    		                hidden:true
    		            }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});