/*
 * File: app/view/ktsb/ktsbView.js
 * 
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 * 
 * This file requires use of the Ext JS 4.2.x library, under independent
 * license. License of Sencha Architect does not include license for Ext JS
 * 4.2.x. For more details see http://www.sencha.com/license or contact
 * license@sencha.com.
 * 
 * This file will be auto-generated each and everytime you save your project.
 * 
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ktsb.ktsbView', {
			extend : 'Ext.panel.Panel',
			alias : 'widget.ktsbView',

			layout : {
				align : 'stretch',
				type : 'vbox'
			},
			title : '课题上报',

			initComponent : function() {
				var me = this;
				Ext.apply(Ext.form.field.VTypes, {
			        daterange1: function(val, field) {
			            var date = field.parseDate(val);
			
			            if (!date) {
			                return false;
			            }
			            if (field.startDateField && (!this.dateRangeMax || (date.getTime() != this.dateRangeMax.getTime()))) {
			                var start = field.up('form').down('#' + field.startDateField);
			                start.setMaxValue(date);
			                start.validate();
			                this.dateRangeMax = date;
			            }
			            else if (field.endDateField && (!this.dateRangeMin || (date.getTime() != this.dateRangeMin.getTime()))) {
			                var end = field.up('form').down('#' + field.endDateField);
			                end.setMinValue(date);
			                end.validate();
			                this.dateRangeMin = date;
			            }
			            /*
			             * Always return true since we're only using this vtype to set the
			             * min/max allowed values (these are tested for after the vtype test)
			             */
			            return true;
			        },

		            daterangeText: '开始日期必须大于结束日期'
		        });	
				Ext.applyIf(me, {
							items : [{
										id : 'kt_ktsb_grid',
										xtype : 'ktgrid',
                                        flag:'dw',
										flex : 0.4,
										height : 320,
										autoScroll : true,
										collapsed : false,
										collapsible : true,
										title : '课题列表',
										tbar2 : [/*{
													xtype : 'tbseparator'
												},
												{
													xtype : 'button',
													itemId : 'ktlist_edit',
													iconCls : 'icon-edit',
													text : '编辑'
												},*/
												{
													xtype : 'tbseparator',
													id:'ktlist_comments_tbseparator_id'
												},
												{
													xtype : 'button',
													itemId : 'ktlist_comments',
													iconCls : 'icon-comments',
													id:'ktlist_comments_button_id',
													text : '意见回复'
												},	
												{
													xtype : 'tbseparator'
												},
												{
													xtype : 'button',
													itemId : 'ktlist_opinionView',
													iconCls : 'icon-modify-history',
													text : '查看回复意见'
												},	
												{
													xtype : 'tbseparator'
												}]
									}, {
										itemId:'ktsb_Big_Form',
										id:'ktsb_Big_Form_Id',
										xtype : 'tabpanel',
										flex : 0.6,
										border : false,
										collapsible : false,
										activeTab : 0,
										items : [{
													// 基本信息
													xtype : 'ktsbBasicInfoForm',
													id : 'ktsbBasicForm'

												}, {
													// 责任人
													xtype : 'ktsbPeopleInchargeForm',
													id : 'ktsbPeopleInchargeForm'
												}, {
													// 支持单位
													xtype : 'ktsbMemberOrgForm',
													id : 'ktsbMemberOrgForm'
												}, {
													// 必要性分析
													xtype : 'ktsbNecessityForm',
													id : 'ktsbNecessityForm'
												}, {
													// 总体目标及指标
													xtype : 'ktsbObjAndKpiForm',
													id : 'ktsbObjAndKpiForm'

												}, {
													// 技術方案
													xtype : 'ktsbSolutionForm',
													id : 'ktsbSolutionForm'
												}, {
													// 基础条件及优势
													xtype : 'ktsbCapabilityForm',
													id : 'ktsbCapabilityForm'
												}, {
													// 组织及管理
													xtype : 'ktsbOrgAndMngForm',
													id : 'ktsbOrgAndMngForm'
												}, {
													// 经费预算
													xtype : 'ktsbBudgetForm',
													id : 'ktsbBudgetForm'

												}, {
													// 风险分析及对策
													xtype : 'ktsbRisksForm',
													id : 'ktsbRisksForm'
												}, {
													// 经费及任务分解
													xtype : 'ktsbTaskBreakdownForm',
													id : 'ktsbTaskBreakdownForm'
												}]
									}],
							dockedItems : [{
										xtype : 'toolbar',
										flex : 1,
										id:'ktsbView_toolber_save',
										dock : 'bottom',
										items : [{
													xtype : 'tbseparator'
												}, {
													xtype : 'button',
													itemId : 'ktsbBccg',
													iconCls : 'icon-save',
													text : '保存草稿'
												}, {
													xtype : 'tbseparator'
												}, {
													xtype : 'button',
													itemId : 'ktsbBigFormSubmit',
													iconCls : 'icon-submit',
													text : '提交'
												}]
									}]
						});

				me.callParent(arguments);
			}

		});