/*
 * File: app/controller/ktsb/ktsbCtrl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.controller.ktsb.ktsbCtrl', {
    extend: 'Ext.app.Controller',
    views: [
        'ktsb.ktsbView','ktsb.ktsbBasicInfoForm','ktsb.ktsbPeopleInchargeForm', 
        'ktsb.ktsbMemberOrgForm', 'ktsb.ktsbNecessityForm','ktsb.ktsbObjAndKpiForm', 'ktsb.ktsbSolutionForm',
        'ktsb.ktsbCapabilityForm', 'ktsb.ktsbOrgAndMngForm','ktsb.ktsbBudgetForm','ktsb.ktsbRisksForm', 'ktsb.ktsbTaskBreakdownForm',

    	'ktsb.ktsbAddXzPeopleWin','ktsb.ktsbAddCompanyWin','ktsb.ktsbAddTaskTargetWin','ktsb.ktsbAddSfgcWin','ktsb.ktsbAddOtherKtWin',
    	'ktsb.ktsbEditOtherKtWin','ktsb.ktsbEditResearchOutlayWin','ktsb.ktsbEditSpecialistOpinionWin','ktsb.ktsbAddTechPeopleWin',
    	'ktsb.ktsbAddMainPeopleWin'
    ],
    stores:[
    	'com.IssueTypeStore',
        'ktsb.ktsbdwlistStore',
        'ktsb.ktsbkttypeStore',
        'ktsb.ktsblistStore',
        'ktsb.ktsbmjStore',
        'ktsb.ktsbstatusStore',
        'ktsb.ktsbFormBudgetStore',
        'people.peopleStore',
        'ktsb.ktsbPeopleStore',
        'ktsb.ktsbSkillPeopleStore',
        'ktsb.ktxxTaskTargetStore',
        'ktsb.ktxxSfgcStore',
        'ktsb.ktsbMainPeopleStore',
        'ktsb.ktsbResearchOutlayStore',
        'opinion.issueOpinionStore'
    ],

    init: function(application) {
		this.tabActiveTabArray = new Array();
        //debugger;
        this.control({
        	
/******begin 主页面******/
			'ktsbView gridpanel[xtype=ktgrid]': {
             	itemclick:this.ktsbViewItemclick
             },
            'ktsbView #ktsb_Big_Form':{  //tabpanel 点击事件
            	tabchange:this.ktsb_tabpanel_tabchangeEvent
            },
            
            'ktsbView #ktsbBccg':{//保存草稿
            	click:this.ktlistSaveEvent
            },
            'ktsbView #ktsbBigFormSubmit':{//保存草稿
//            	click:this.ktsbBigFormSubmitEvent
            	click:this.ktlistSaveEvent
            },
           
            'ktsbView #ktlist_edit':{ //主页面： 编辑按钮
                click:this.ktlistEditEvent
            },
            
            'ktsbView #ktlist_opinionView':{////主页面： 查看意见按钮
            	click:this.ktlistOpinionViewEvent
            },
/******end 主页面******/      
            
            
/******begin 基本信息******/
            'ktsbView #sbdw_wsxx':{ //基本信息页面：完善信息功能 --->shop
                click:this.ktlistSbdwWsxxEvent
            },
/******end 基本信息******/
            
            
/******begin 专家意见回复******/
            'ktsbView #ktlist_comments':{ //专家意见回复按钮
            	click:this.ktlistCommentsEvent
            },
            'ktsbEditSpecialistOpinionWin button[action=ktsb_ktsbEditSpecialistOpinionWin_exec_act]':{  //专家意见回复窗体-执行
		    	click:this.ktsb_specialistOpinion_execEvent
		    },
		    
		    'ktsbEditSpecialistOpinionWin button[action=ktsb_ktsbEditSpecialistOpinionWin_cancel_act]':{ //专家意见回复窗体-关闭
		    	click:this.ktsb_specialistOpinion_closeEvent
		    },
		    
		    'ktsbEditSpecialistOpinionWin gridpanel[id=ktsbEditSpecialistOpinionWin_issueOpinionData]':{ //专家意见回复窗体-选择
		    	itemclick:this.issueOpinionWin_Itemclick
		    },
/******begin 专家意见回复******/
		    
		    
		    
/******begin 责任人信息******/
            /**(行政责任人)**/
            'ktsbView #ktsb_People_add':{//添加按钮
            	click:this.ktsb_People_addEvent
            },
            'ktsbView #ktsb_People_del':{//删除按钮
            	click:this.ktsb_People_delEvent
            },
            
            'ktsbAddXzPeopleWin #ktsb_people_xz_zrr_add':{//添加行政责任人窗体-提交按钮
            	click:this.ktsb_people_xz_zrr_addEvent
            },
            'ktsbAddXzPeopleWin #ktsb_people_xz_zrr_close':{//添加行政责任人窗体-关闭按钮
            	click:this.ktsb_people_xz_zrr_closeEvent
            },
             'ktsbAddXzPeopleWin #ktsb_people_xz_zrr':{//添加行政责任人窗体-责任人下拉框
            	change:this.ktsb_people_xz_zrrEvent
            },
            
            
            /**(技术负责人)**/
            'ktsbView #ktsb_SkillPeople_add':{//添加按钮
            	click:this.ktsb_SkillPeople_addEvent
            },
            'ktsbView #ktsb_SkillPeople_del':{//删除按钮
            	click:this.ktsb_SkillPeople_delEvent
            },
            
            'ktsbAddTechPeopleWin #ktsb_people_tech_zrr_add':{//添加技术责任人窗体-提交按钮
            	click:this.ktsb_people_xz_zrr_addEvent
            },
            'ktsbAddTechPeopleWin #ktsb_people_tech_zrr_close':{//添加技术责任人窗体-关闭按钮
            	click:this.ktsb_people_tech_zrr_closeEvent
            },
            'ktsbAddTechPeopleWin #ktsb_people_tech_zrr':{//添加技术责任人窗体-责任人下拉框
            	change:this.ktsb_people_tech_zrrEvent
            },
            
/******end 责任人信息页面******/            
		    
            
            
/******begin 支持单位信息******/		    
             'ktsbView #ktsb_zcdw_del':{//删除按钮
                click:this.ktlistZcdwDelEvent
            },
            'ktsbView #ktsb_zcdw_add':{//添加按钮
            	click:this.ktsb_zcdw_addEvent
                
            },
            'ktsbView #ktsb_zcdw_edit':{//编辑功能--->shop
                click:this.ktlistZcdwEditEvent
            },
            'ktsbAddCompanyWin #ktsb_companyName_combobox':{//支持单位信息页面：添加支持单位窗体-单位名称下拉框
            	change:this.ktsb_companyName_comboboxEvent
            },
            'ktsbAddCompanyWin #ktsb_company_add':{//支持单位信息页面：添加支持单位窗体-保存按钮
            	click:this.ktsb_company_addEvent
            },
            'ktsbAddCompanyWin #ktsb_company_close':{//支持单位信息页面：添加支持单位窗体-关闭按钮
            	click:this.ktsb_company_closeEvent
            },
            
            'ktsbAddCompanyWin combobox[id=ktsbAddCompanyWin_belongAreaProvince]': {//支持单位信息页面：添加支持单位窗体-市级下拉框
            	select:this.select_AddCompanyWin_belongAreaProvince
            },
            
            'ktsbAddCompanyWin combobox[id=ktsbAddCompanyWin_belongAreaCity]': {//支持单位信息页面：添加支持单位窗体-区级下拉框
            	select:this.select_AddCompanyWin_belongAreaCity
            },
            
            
/******end 支持单位信息******/	   
            

/******begin 总体目标及指标******/	
			/**(年度任务)**/
             'ktsbView #ktsb_tasktarget_add':{//添加按钮
                click:this.ktsb_tasktarget_addEvent
            },
            'ktsbView #ktsb_tasktarget_edit':{//编辑按钮
            	click:this.ktsb_tasktarget_editEvent
            },
            'ktsbView #ktsb_tasktarget_del':{//删除按钮
            	click:this.ktsb_tasktarget_delEvent
            },
            'ktsbAddTaskTargetWin #ktsb_tasktargetWin_add':{//添加年度任务指标窗体-保存按钮
            	click:this.ktsb_tasktarget_addWinEvent
            },
             'ktsbAddTaskTargetWin #ktsb_tasktargetWin_close':{//添加年度任务指标窗体-关闭按钮
            	click:this.ktsb_tasktarget_closeWinEvent
            },
            
			/**(工程配套)**/
            'ktsbView #ktsb_sfgc_add':{//添加按钮
                click:this.ktsb_sfgc_addEvent
            },
            'ktsbView #ktsb_sfgc_edit':{//编辑按钮
            	click:this.ktsb_sfgc_editEvent
            },
            'ktsbView #ktsb_sfgc_del':{//删除按钮
            	click:this.ktsb_sfgc_delEvent
            },
            'ktsbAddSfgcWin #ktsb_sfgcWin_add':{//主要示范工程与配套条件窗体-保存按钮
            	click:this.ktsb_sfgc_addWinEvent
            },
            'ktsbAddSfgcWin #ktsb_sfgcWin_close':{//主要示范工程与配套条件窗体-关闭按钮
            	click:this.ktsb_sfgc_closeWinEvent
            },
/******end 总体目标及指标******/	
            
            
/******begin 基础条件及优势******/
            
			/**(主要人员情况)**/	
            'ktsbView #ktsb_mainPeople_add':{//添加按钮
                click:this.ktsb_mainPeople_addEvent
            },
            'ktsbView #ktsb_mainPeople_del':{//删除按钮
                click:this.ktsb_mainPeople_delEvent
            },
            'ktsbAddMainPeopleWin #ktsb_main_people_add':{//添加主要人员窗体-提交
            	click:this.ktsb_people_xz_zrr_addEvent
            },
            'ktsbAddMainPeopleWin #ktsb_main_people_close':{//添加主要人员窗体-关闭
            	click:this.ktsb_main_people_closeEvent
            },
            'ktsbAddMainPeopleWin #ktsb_main_people':{//添加主要人员窗体-责任人下拉框
            	change:this.ktsb_main_people_event
            },
            
            
            
			/**(目前承担其他课题情况)**/
            'ktsbView #ktsb_qtkt_add':{//添加按钮
                click:this.ktsb_qtkt_addEvent
            },
            'ktsbView #ktsb_qtkt_edit':{//编辑按钮
                click:this.ktsb_qtkt_editEvent
            },
            'ktsbView #ktsb_qtkt_del':{//删除按钮
                click:this.ktsb_qtkt_delEvent
            },
            'qtktAddWin button[action=ktsb_qtkt_add_cancel_act]':{//添加其他课题信息窗体-关闭按钮
                click:this.ktsb_qtkt_add_cancelEvent
            },
            'qtktAddWin button[action=ktsb_qtkt_add_exec_act]' : {//添加其他课题信息窗体-保存按钮
                click: this.ktsb_qtkt_add_execEvent
            },
            
            'qtktEditWin button[action=ktsb_qtkt_edit_cancel_act]':{//修改其他课题信息窗体-关闭按钮
                click:this.ktsb_qtkt_edit_cancelEvent
            },
            'qtktEditWin button[action=ktsb_qtkt_edit_exec_act]' : {//修改其他课题信息窗体-保存按钮
                click: this.ktsb_qtkt_edit_execEvent
            },
/******end 基础条件及优势******/            

        
            
/******begin 经费及任务分析******/
			/**(研究经费按单位分配)**/
            'ktsbView #ktsb_researchOutlay_add':{//添加按钮
                click:this.ktsb_researchOutlay_addEvent
            },
            'ktsbView #ktsb_researchOutlay_edit':{//编辑按钮
                click:this.ktsb_researchOutlay_editEvent
            },
            'ktsbView #ktsb_researchOutlay_del':{//删除按钮
                click:this.ktsb_researchOutlay_delEvent
            },
            'ktsbEditResearchOutlayWin button[action=ktsb_researchOutla_exec_act]' : {//研究经费按单位分配窗体-保存按钮
                click: this.ktsb_researchOutlay_win_execEvent
            },
            'ktsbEditResearchOutlayWin button[action=ktsb_researchOutla_cancel_act]' : {//研究经费按单位分配窗体-关闭按钮
                click: this.ktsb_researchOutlay_win_cancelEvent
            },
            
            
			/**(研究任务设置)**/
            'ktsbView #ktsb_research_task_add':{//添加按钮
                click:this.ktsb_research_task_addEvent
            },
            'ktsbView #ktsb_research_task_edit':{//编辑按钮
                click:this.ktsb_research_task_editEvent
            },'ktsbView #ktsb_research_task_del':{//删除按钮
                click:this.ktsb_research_task_delEvent
            },
            
            'researchTaskAddWin button[action=ktsb_research_task_add_cancel_act]':{//添加研究任务设置窗体-关闭按钮
                click:this.ktsb_research_task_add_cancelEvent
            },
            'researchTaskAddWin button[action=ktsb_research_task_add_exec_act]' : {//添加研究任务设置窗体-保存按钮
                click: this.ktsb_research_task_add_execEvent
            },
            
            'researchTaskEditWin button[action=ktsb_research_task_edit_cancel_act]':{//编辑研究任务设置窗体-关闭按钮
                click:this.ktsb_research_task_edit_cancelEvent
            },
            'researchTaskEditWin button[action=ktsb_research_task_edit_exec_act]' : {//编辑研究任务设置窗体-保存按钮
                click: this.ktsb_research_task_edit_execEvent
            }
 /******end 经费及任务分析******/           
        });
    },
    
/****begin 主页面****/
	ktsbViewItemclick:function(obj, record, item, index, e, eOpts){
		this.ktsbId=record.data.id;
		this.ktsblistRecord = record;
		if(record.data.status==1||record.data.status==3){
			Ext.getCmp("ktsbView_toolber_save").show();
		}else{
			Ext.getCmp("ktsbView_toolber_save").hide();
		}
		
		if(record.data.status==3){
			Ext.getCmp("ktlist_comments_tbseparator_id").show();
			Ext.getCmp("ktlist_comments_button_id").show();
		}else{
			Ext.getCmp("ktlist_comments_tbseparator_id").hide();
			Ext.getCmp("ktlist_comments_button_id").hide();
		}
		
    	var panelId= Ext.getCmp('ktsb_Big_Form_Id').getActiveTab();
    	var tabpanel= Ext.getCmp('ktsb_Big_Form_Id');
    	this.myMask = new Ext.LoadMask(tabpanel, 
    		{
    		msg:"Please wait...",
    		removeMask:true
    		});
		this.myMask.show();
		
    	tabpanel.setActiveTab(0);
    	this.initFromMsg('ktsbBasicForm');
    	
    	tabpanel.setActiveTab(1);
    	this.initFromMsg('ktsbPeopleInchargeForm');
    	
    	tabpanel.setActiveTab(2);
    	this.initFromMsg('ktsbMemberOrgForm');
    	
    	tabpanel.setActiveTab(3);
    	this.initFromMsg('ktsbNecessityForm');
    	
    	tabpanel.setActiveTab(4);
    	this.initFromMsg('ktsbObjAndKpiForm');
    	
    	tabpanel.setActiveTab(5);
    	this.initFromMsg('ktsbSolutionForm');
    	
    	tabpanel.setActiveTab(6);
    	this.initFromMsg('ktsbCapabilityForm');
    	
    	tabpanel.setActiveTab(7);
    	this.initFromMsg('ktsbOrgAndMngForm');
    	
    	tabpanel.setActiveTab(8);
    	this.initFromMsg('ktsbBudgetForm');
    	
    	tabpanel.setActiveTab(9);
    	this.initFromMsg('ktsbRisksForm');
    	
    	tabpanel.setActiveTab(10);
    	this.initFromMsg('ktsbTaskBreakdownForm');
    	
    	tabpanel.setActiveTab(panelId);
    	
		this.myMask.hide(); //隐藏
		//debugger;
	},
	
	ktsb_tabpanel_tabchangeEvent:function(tabPanel,newCard,oldCard,eOpts){
		/*var grid = Ext.ComponentQuery.query('ktsbView gridpanel')[0];
       	var rowRecord = grid.getSelectionModel().selected.items[0];
       	if(rowRecord == undefined) {
           return;
       	}*/
		if(this.ktsbId==undefined){
			return;
		}
       	//this.initFromMsg(newCard.getId());
	},
	
    ktlistSaveEvent: function(button,e,eOpts) {
    	var flag ;
    	if(button.itemId =="ktsbBccg"){
    		flag = false;
    	}else if(button.itemId == "ktsbBigFormSubmit"){
    		flag = true;
    	}
    	if(this.ktsbId == undefined){
    		Ext.Msg.alert('Infomation','请选择一条指定的课题再进行保存！');
    		return ;
    	}
    	/**基本信息**/
    	var ktsbBasicForm = Ext.JSON.encode(Ext.getCmp('ktsbBasicForm').getForm().getValues());
    	/**责任人信息**/
    	var peopleStore = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbPeopleGrid]')[0].getStore();
    	var skillpeopleStore = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbSkillPeopleGrid]')[0].getStore();
    	/**支持单位信息**/
    	var companyStore = Ext.ComponentQuery.query('ktsbMemberOrgForm gridpanel[itemId=ktsbCompanyListGrid]')[0].getStore();
    	/**必要性分析**/
    	var necessitytext = Ext.JSON.encode(Ext.getCmp('ktsbNecessityForm').getForm().getValues().necessitytext);//必要性分析
    	/**总体目标及指标**/
    	var objAndKpitext = Ext.JSON.encode(Ext.getCmp('ktsbObjAndKpiForm').getForm().getValues().objAndKpitext); //总体目标及指标说明
    	var taskTargetStore = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxTaskTargetGrid]')[0].getStore();//年度任务及指标
    	var sfgcStore = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxsfgcGrid]')[0].getStore();//总体工程及配套条件
    	/**技术方案**/
    	var solutiontext = Ext.JSON.encode(Ext.getCmp('ktsbSolutionForm').getForm().getValues().solutiontext);//技术方案
    	/**基础条件及优势**/
    	var advantagetext = Ext.JSON.encode(Ext.getCmp('ktsbCapabilityForm').getForm().getValues().advantagetext);//基础条件和优势
    	var mainPeopletext =  Ext.JSON.encode(Ext.getCmp('ktsbCapabilityForm').getForm().getValues().mainPeopletext);//负责人及骨干人员
    	var capabilityStore = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel[itemId=ktsbCapabilityPeopleGrid]')[0].getStore();//主要人员情况
    	var otherKtStore = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel[itemId=ktsbOtherKtGrid]')[0].getStore();//其他课题情况
    	/**课题组织及管理机制**/
    	var orgAndMngtext = Ext.JSON.encode(Ext.getCmp('ktsbOrgAndMngForm').getForm().getValues().orgAndMngtext);
    	/**风险分析及对策**/
    	var riskstext = Ext.JSON.encode(Ext.getCmp('ktsbRisksForm').getForm().getValues().riskstext);
    	 /**经费预算**/
    	var budgetRootNode = Ext.ComponentQuery.query('ktsbBudgetForm panel[itemId=ktsbBudgetGrid]')[0].getRootNode();//经费预算
    	var treefields = ['text','budgetID','budgetName','id','investmentBank','investmentCenGov','investmentEnterprise','investmentLocGov',
    						'investmentOther','investmentSum','issueID','leaf','nextChild','parentID'];
    	 
    	function getNodeData(budgetRootNode,treefields){
    		
    		var data = {};
    		Ext.each(treefields,function(fieldName){
    			data[fieldName] = budgetRootNode.get(fieldName);
    		});
    		
    		if(budgetRootNode.hasChildNodes()){
    			var children = data.children = [];
    			budgetRootNode.eachChild(function(child){
    				children.push(getNodeData(child,treefields))
    			});
    		}
    		return data;
    	};
    	var nodeList = getNodeData(budgetRootNode,treefields);
    	debugger;
    	/**经费及任务分解**/
    	var researchTaskStore = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel[itemId=ktsbResearchTaskGrid]')[0].getStore();
    	var researchFundStore = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel[itemId=ktsbResearchOutlayPeopleGrid]')[0].getStore();
    	
    	//定义各个模块grid的model数组集合
    	var peopleRecords = [],skillpeopleRecords = [],companyRecords = [],taskTargetRecords = [],sfgcRecords = [],
    		capabilityRecords = [],otherKtRecords = [],researchTaskRecords = [],researchFundRecords = [],
    		budgetRecords = [];
    	
    	Ext.Array.each(peopleStore.getRange(),function(record, index, countriesItSelf){
    		peopleRecords.push(record.data);
    	});
    	Ext.Array.each(skillpeopleStore.getRange(),function(record, index, countriesItSelf){
    		skillpeopleRecords.push(record.data);
    	});
    	Ext.Array.each(companyStore.getRange(),function(record, index, countriesItSelf){
    		companyRecords.push(record.data);
    	});
    	Ext.Array.each(taskTargetStore.getRange(),function(record, index, countriesItSelf){
    		taskTargetRecords.push(record.data);
    	});
    	Ext.Array.each(sfgcStore.getRange(),function(record, index, countriesItSelf){
    		sfgcRecords.push(record.data);
    	});
    	
    	Ext.Array.each(capabilityStore.getRange(),function(record, index, countriesItSelf){
    		capabilityRecords.push(record.data);
    	});
    	Ext.Array.each(otherKtStore.getRange(),function(record, index, countriesItSelf){
    		otherKtRecords.push(record.data);
    	});
    	
    	Ext.Array.each(researchTaskStore.getRange(),function(record, index, countriesItSelf){
    		researchTaskRecords.push(record.data);
    	});
    	Ext.Array.each(researchFundStore.getRange(),function(record, index, countriesItSelf){
    		researchFundRecords.push(record.data);
    	});
    	
    	
    	Ext.Ajax.request({
    		url:'ktsb/draftSave.action?t='+new Date().getTime(),
    		timeout:120000,
    		params:{
    			submitFlag:flag,
    			issueId:this.ktsbId,
    			ktsbBasicForm:ktsbBasicForm,//基本信息
    			ktsbPeoples:Ext.JSON.encode(peopleRecords),//行政责任人
    			skillPeoples:Ext.JSON.encode(skillpeopleRecords),//技术责任人
    			companys:Ext.JSON.encode(companyRecords),//支持单位
    			necessitytext:necessitytext,//必须性分析
    			objAndKpitext:objAndKpitext,//总体目标及指标
    			taskTargets:Ext.JSON.encode(taskTargetRecords),//任务目标
    			sfgcs:Ext.JSON.encode(sfgcRecords),//示范工程及配套条件
    			solutiontext:solutiontext,//技术方案
    			advantagetext : advantagetext,//基础条件和优势
    			mainPeopletext : mainPeopletext,//负责人及骨干人员
    			capabilitys : Ext.JSON.encode(capabilityRecords),////主要人员情况
    			otherKt : Ext.JSON.encode(otherKtRecords),//其他课题情况
    			orgAndMngtext : orgAndMngtext,//课题组织及管理机制
    			riskstext : riskstext,//风险分析及对策
    			researchTasks : Ext.JSON.encode(researchTaskRecords),//研究任务设置
    			researchFunds : Ext.JSON.encode(researchFundRecords),//研究经费按单位分配
    			budgets:Ext.JSON.encode(nodeList)
    		},
    		success:function(response,options){
    			 Ext.Msg.alert('Infomation','课题材料保存成功！');
    			 var grid = Ext.getCmp('kt_ktsb_grid');
				 grid.getSelectionModel().deselectAll();
				 var store = grid.getStore();
				 store.load({ params: {}});
    		},
    		failure:function(response,options){
    			 Ext.Msg.alert('Infomation','课题材料保存失败！');
    		}
    	});
       
    },
	
    
    ktlistEditEvent: function() {
    	var panelId= Ext.getCmp('ktsb_Big_Form_Id').getActiveTab().id;
    	if(this.ktsblistRecord == undefined){
    		Ext.Msg.alert('Infomation','请选择一个课题再进行编辑！');
    	}else{
    		this.tabActiveTabArray = new Array();
    		this.ktsbId=this.ktsblistRecord.data.id;
    		this.initFromMsg(panelId);
    	}
//        Ext.Msg.alert('Infomation','课题上报->课题列表->编辑事件');
    },
	
	
    initFromMsg:function(panelId){
    	// !Ext.Array.contains(this.tabActiveTabArray,panelId)
    	if(panelId == 'ktsbBasicForm'){
    		
    		if(this.ktsbId != undefined){
    			Ext.Ajax.request({
    				url:'ktsb/bflistall.action?t='+new Date().getTime(),
    				method:'POST',
    				params:{
    					issueId:this.ktsbId
    				},
    				success:function(form,action){
    					var res = Ext.JSON.decode(form.responseText);
    					Ext.getCmp('ktsbBasicForm').getForm().reset();
    					Ext.getCmp('ktsbBasicForm').getForm().setValues(res);
    				},
    				failure:function(form,action){
    					Ext.Msg.alert('Infomation','获取基本信息数据失败！');
    				}
    			
    			});
    		}
			//基本信息
		}else if(panelId == 'ktsbPeopleInchargeForm'){
			this.storeDirectorWithCondition();//行政责任人
			this.storeTechmemberWithCondition();//技术责任人
			//责任人
		}else if(panelId == 'ktsbMemberOrgForm'){
			this.storeCompanyWithCondition();
			//支持单位
		}else if(panelId == 'ktsbNecessityForm'){
			Ext.Ajax.request({
    			url:'ktsb/findktxxtext.action?t='+new Date().getTime(),
    			params:{
    				issueId:this.ktsbId
    			},
    			success:function(response,action){
    				ktxxText = Ext.JSON.decode(response.responseText);
    				//Ext.ComponentQuery.query('ktsbNecessityForm htmleditor')[0].setValue('');
    				//Ext.ComponentQuery.query('ktsbNecessityForm htmleditor')[0].setValue(ktxxText.necessitytext);
    				Ext.getCmp("ktsbNecessityForm_necessitytext").setValue(ktxxText.necessitytext);
    				
    			}
    		});
			//必要性分析
		}else if(panelId == 'ktsbObjAndKpiForm'){
			//总体目标及指标
			Ext.Ajax.request({
    			url:'ktsb/findktxxtext.action?t='+new Date().getTime(),
    			params:{
    				issueId:this.ktsbId
    			},
    			success:function(response,action){
    				ktxxText = Ext.JSON.decode(response.responseText);
    				Ext.ComponentQuery.query('ktsbObjAndKpiForm htmleditor[name=objAndKpitext]')[0].setValue('');
    				Ext.ComponentQuery.query('ktsbObjAndKpiForm htmleditor[name=objAndKpitext]')[0].setValue(ktxxText.objective);
    			}
    		});
		}else if(panelId == 'ktsbSolutionForm'){
			//技術方案
			Ext.Ajax.request({
    			url:'ktsb/findktxxtext.action?t='+new Date().getTime(),
    			params:{
    				issueId:this.ktsbId
    			},
    			success:function(response,action){
    				ktxxText = Ext.JSON.decode(response.responseText);
    				Ext.ComponentQuery.query('ktsbSolutionForm htmleditor[name=solutiontext]')[0].setValue('')
    				Ext.ComponentQuery.query('ktsbSolutionForm htmleditor[name=solutiontext]')[0].setValue(ktxxText.techsolution);
    			}
    		});
		}else if(panelId == 'ktsbCapabilityForm'){
			this.storeMainPeopleWithCondition();
			this.storeQueryWithCondition();
			//基础条件及优势
			Ext.Ajax.request({
    			url:'ktsb/findktxxtext.action?t='+new Date().getTime(),
    			params:{
    				issueId:this.ktsbId
    			},
    			success:function(response,action){
    				ktxxText = Ext.JSON.decode(response.responseText);
    				Ext.ComponentQuery.query('ktsbCapabilityForm htmleditor[name=advantagetext]')[0].setValue('');
    				Ext.ComponentQuery.query('ktsbCapabilityForm htmleditor[name=mainPeopletext]')[0].setValue('');
    				
    				Ext.ComponentQuery.query('ktsbCapabilityForm htmleditor[name=advantagetext]')[0].setValue(ktxxText.basisinfo);
    				Ext.ComponentQuery.query('ktsbCapabilityForm htmleditor[name=mainPeopletext]')[0].setValue(ktxxText.memberinfo);
    			}
    		});
		}else if(panelId == 'ktsbOrgAndMngForm'){
			//组织及管理
			Ext.Ajax.request({
    			url:'ktsb/findktxxtext.action?t='+new Date().getTime(),
    			params:{
    				issueId:this.ktsbId
    			},
    			success:function(response,action){
    				ktxxText = Ext.JSON.decode(response.responseText);
    				Ext.ComponentQuery.query('ktsbOrgAndMngForm htmleditor[name=orgAndMngtext]')[0].setValue('');
    				Ext.ComponentQuery.query('ktsbOrgAndMngForm htmleditor[name=orgAndMngtext]')[0].setValue(ktxxText.orgmanager);
    			}
    		});
		}else if(panelId == 'ktsbBudgetForm'){
			this.budgetStoreload();//加载预算
			//经费预算
		}else if(panelId == 'ktsbRisksForm'){
			//风险分析及对策
			Ext.Ajax.request({
    			url:'ktsb/findktxxtext.action?t='+new Date().getTime(),
    			params:{
    				issueId:this.ktsbId
    			},
    			success:function(response,action){
    				ktxxText = Ext.JSON.decode(response.responseText);
    				Ext.ComponentQuery.query('ktsbRisksForm htmleditor[name=riskstext]')[0].setValue('');
    				Ext.ComponentQuery.query('ktsbRisksForm htmleditor[name=riskstext]')[0].setValue(ktxxText.riskstext);
    			}
    		});
		}else if(panelId == 'ktsbTaskBreakdownForm'){
			//经费及任务分解
			this.storeResearchTaskWithCondition();//研究任务设置
	      	this.commonResearchOutlayCallback();//研究经费按单位分配
		}
		//Ext.Array.include(this.tabActiveTabArray,panelId);
//		Ext.Ajax.request({
//    			url:'ktsb/findktxxtext.action',
//    			params:{
//    				issueId:this.ktsbId
//    			},
//    			success:function(response,action){
//    				ktxxText = Ext.JSON.decode(response.responseText);
//    				Ext.ComponentQuery.query('ktsbNecessityForm htmleditor')[0].setValue(ktxxText.necessitytext);
//    				Ext.ComponentQuery.query('ktsbObjAndKpiForm htmleditor[name=objAndKpitext]')[0].setValue(ktxxText.objective);
//    				Ext.ComponentQuery.query('ktsbSolutionForm htmleditor[name=solutiontext]')[0].setValue(ktxxText.techsolution)
//    				Ext.ComponentQuery.query('ktsbCapabilityForm htmleditor[name=advantagetext]')[0].setValue(ktxxText.basisinfo);
//    				Ext.ComponentQuery.query('ktsbCapabilityForm htmleditor[name=mainPeopletext]')[0].setValue(ktxxText.memberinfo);
//    				Ext.ComponentQuery.query('ktsbOrgAndMngForm htmleditor[name=orgAndMngtext]')[0].setValue(ktxxText.orgmanager);
//    				Ext.ComponentQuery.query('ktsbRisksForm htmleditor[name=riskstext]')[0].setValue(ktxxText.riskstext);
//    			}
//    		});
    },
    
    ktlistOpinionViewEvent:function(){
    	if(this.ktsbId == undefined) {
		   Ext.MessageBox.alert("温馨提示", "请您先选择一行课题列表，再进行操作，谢谢！");
           return;
       	}
       	var url = "ktxx/getXGHistory.action?issueId="+this.ktsbId;
    	window.open(url);
    },
/****end 主页面****/
    
    
/******begin 基本信息******/    
    ktlistSbdwWsxxEvent: function() {
        Ext.Msg.alert('Infomation','课题上报->基本信息->申报单位完善信息事件');
    },
/******end 基本信息******/    
    
    
/***begin 专家意见回复**/
     ktlistCommentsEvent:function(){ //专家意见回复
        if(this.ktsbId == undefined) {
		   Ext.MessageBox.alert("温馨提示", "请您先选择一行课题列表，再进行操作，谢谢！");
           return;
       	}
    	if (this.ktsbSpecialistOpinionWin == null || this.ktsbSpecialistOpinionWin == undefined) {
            this.ktsbSpecialistOpinionWin = Ext.create('App.view.ktsb.ktsbEditSpecialistOpinionWin');
        }
        this.ktsbSpecialistOpinionWin.show();
        //this.storeSpecialistOpinionCondition();
        this.initKtsbEditSpecialistOpinionWinData();
    },
    
    initKtsbEditSpecialistOpinionWinData:function(){
    	Ext.Ajax.request({
	            url: 'ktsb/findIssueOpinionByIssueId.action?t='+new Date().getTime(),
	            actionMethods:{
					read:'POST'        
		        },
		        params: {
					issueId:this.ktsbId
	            },
	            success: function (response){
	            	var jsonResult = response.responseText;
	            	if(jsonResult!=undefined){
	            		var opinion=Ext.decode(jsonResult);//opinion.issueOpinion.
	            		if(opinion.issueOpinion!=null){
	            			Ext.getCmp('ktsbEditSpecialistOpinionWin_bottom_panel').setVisible(true);
	            			Ext.getCmp('ktsbEditSpecialistOpinionWin_top_panel').setVisible(false);
	            			
	            			
	            			Ext.getCmp('ktsbEditSpecialistOpinionWin_opinionId').setValue(opinion.issueOpinion.id);
					        Ext.getCmp('ktsbEditSpecialistOpinionWin_issueId').setValue(opinion.issueOpinion.issueId);
					        Ext.getCmp('ktsbEditSpecialistOpinionWin_issueStatus').setValue(opinion.issueOpinion.issueStatus);
					        Ext.getCmp('ktsbEditSpecialistOpinionWin_peopleId').setValue(opinion.issueOpinion.peopleId);
					        Ext.getCmp('ktsbEditSpecialistOpinionWin_name').setValue(opinion.issueOpinion.name);
					        
					        var fieldset_issueXsJbxx=Ext.getCmp('issueXsJbxx_fieldset'); //1
					        var opinionWin_issueXsJbxx=Ext.getCmp('opinionWin_issueXsJbxx');
					        if(opinion.issueOpinion.issueXsJbxx!=''){
					        	fieldset_issueXsJbxx.show();
					        	opinionWin_issueXsJbxx.setValue(opinion.issueOpinion.issueXsJbxx);
					        }else{
					        	fieldset_issueXsJbxx.hide();
					        }
					        
					        
					        var fieldset_issueXsCydwRy=Ext.getCmp('issueXsCydwRy_fieldset');//2
					        var opinionWin_issueXsCydwRy=Ext.getCmp('opinionWin_issueXsCydwRy');
					        if(opinion.issueOpinion.issueXsCydwRy!=''){
					        	fieldset_issueXsCydwRy.show();
					        	opinionWin_issueXsCydwRy.setValue(opinion.issueOpinion.issueXsCydwRy);
					        }else{
					        	opinionWin_issueXsCydwRy.setValue('');
					        	fieldset_issueXsCydwRy.hide();	
					        }
					        
					        
					        var fieldset_issueXsJfsc=Ext.getCmp('issueXsJfsc_fieldset');//3
					        var opinionWin_issueXsJfsc=Ext.getCmp('opinionWin_issueXsJfsc');
					        if(opinion.issueOpinion.issueXsJfsc!=''){
					        	fieldset_issueXsJfsc.show();
					        	opinionWin_issueXsJfsc.setValue(opinion.issueOpinion.issueXsJfsc);
					        }else{
					        	fieldset_issueXsJfsc.hide();	
					        	opinionWin_issueXsJfsc.setValue('');
					        }
					        
					        
					        var fieldset_issueXsRwnrKhzb=Ext.getCmp('issueXsRwnrKhzb_fieldset');//4
					        var opinionWin_issueXsRwnrKhzb=Ext.getCmp('opinionWin_issueXsRwnrKhzb');
					        if(opinion.issueOpinion.issueXsRwnrKhzb!=''){
					        	fieldset_issueXsRwnrKhzb.show();
					        	opinionWin_issueXsRwnrKhzb.setValue(opinion.issueOpinion.issueXsRwnrKhzb);
					        }else{
					        	opinionWin_issueXsRwnrKhzb.setValue('');
					        	fieldset_issueXsRwnrKhzb.hide();	
					        }
					        
					        
					        var fieldset_issueXsQt=Ext.getCmp('issueXsQt_fieldset');//5
					        var opinionWin_issueXsQt=Ext.getCmp('opinionWin_issueXsQt');
					        if(opinion.issueOpinion.issueXsQt!=''){
					        	fieldset_issueXsQt.show();	
					        	opinionWin_issueXsQt.setValue(opinion.issueOpinion.issueXsQt);
					        }else{
					        	opinionWin_issueXsQt.setValue('');
					        	fieldset_issueXsQt.hide();	
					        }
					        
					        
					        var fieldset_issueWpYjhz=Ext.getCmp('issueWpYjhz_fieldset');//6
					        var opinionWin_issueWpYjhz=Ext.getCmp('opinionWin_issueWpYjhz');
					        if(opinion.issueOpinion.issueWpYjhz!=''){
					        	fieldset_issueWpYjhz.show();	
					        	opinionWin_issueWpYjhz.setValue(opinion.issueOpinion.issueWpYjhz);
					        }else{
					        	opinionWin_issueWpYjhz.setValue('');
					        	fieldset_issueWpYjhz.hide();	
					        }
					        
					        
					        var fieldset_issueHyscYj=Ext.getCmp('issueHyscYj_fieldset');//7
					        var opinionWin_issueHyscYj=Ext.getCmp('opinionWin_issueHyscYj');
					        if(opinion.issueOpinion.issueHyscYj!=''){
					        	fieldset_issueHyscYj.show();
					        	opinionWin_issueHyscYj.setValue(opinion.issueOpinion.issueHyscYj);
					        }else{
					        	opinionWin_issueHyscYj.setValue('');
					        	fieldset_issueHyscYj.hide();	
					        }
					        
					        
					        var fieldset_issueFsXgws=Ext.getCmp('issueFsXgws_fieldset');//8
					        var opinionWin_issueFsXgws=Ext.getCmp('opinionWin_issueFsXgws');
					        if(opinion.issueOpinion.issueFsXgws!=''){
					        	fieldset_issueFsXgws.show();	
					        	opinionWin_issueFsXgws.setValue(opinion.issueOpinion.issueFsXgws);
					        }else{
					        	opinionWin_issueFsXgws.setValue('');
					        	fieldset_issueFsXgws.hide();
					        }
					        
					        
					        var fieldset_issueFsFsyj=Ext.getCmp('issueFsFsyj_fieldset');//9
					        var opinionWin_issueFsFsyj=Ext.getCmp('opinionWin_issueFsFsyj');
					        if(opinion.issueOpinion.issueFsFsyj!=''){
					        	fieldset_issueFsFsyj.show();	
					        	opinionWin_issueFsFsyj.setValue(opinion.issueOpinion.issueFsFsyj);
					        }else{
					        	opinionWin_issueFsFsyj.setValue('');
					        	fieldset_issueFsFsyj.hide();
					        }
					        
					        
					        
	            		}else{
	            			Ext.getCmp('ktsbEditSpecialistOpinionWin_top_panel').setVisible(true);
	            			Ext.getCmp('ktsbEditSpecialistOpinionWin_bottom_panel').setVisible(false);
	            		}
	            	}else{
	            		Ext.getCmp('ktsbEditSpecialistOpinionWin_top_panel').setVisible(true);
	            		Ext.getCmp('ktsbEditSpecialistOpinionWin_bottom_panel').setVisible(false);
	            	}
	            }
    	});
    },
    
    ktsb_specialistOpinion_execEvent:function(){//专家意见回复窗体-执行
    	
    	if(this.issueOpinionRecord == undefined) {
	           return;
       		}
	       Ext.Ajax.request({
	            url: 'ktsb/editOpinionReplay.action?t='+new Date().getTime(),
	            actionMethods:{
					read:'POST'        
		        },
	            //params: this.ktsbSpecialistOpinionWin.down('form').getForm().getValues(),
	            params:Ext.getCmp('ktsbEditSpecialistOpinionWin_form').getForm().getValues(),
	            success: function (response){
	            	var text = response.responseText;
	            	this.storeSpecialistOpinionCondition();
	            	Ext.MessageBox.alert("提示", "操作成功");
	            },
	            scope: this
	        });
    },
    
    storeSpecialistOpinionCondition:function(){
       var store = Ext.ComponentQuery.query('ktsbEditSpecialistOpinionWin gridpanel')[0];
       store.getSelectionModel().deselectAll();
       store.getStore().load({ params: {issueId:this.ktsbId}});
       this.ktsbSpecialistOpinionWin.down('form').getForm().reset();
    },
    
    ktsb_specialistOpinion_closeEvent:function(){//专家意见回复窗体-关闭
    	this.ktsbSpecialistOpinionWin.down('form').getForm().reset();
        Ext.destroy(this.ktsbSpecialistOpinionWin);
        this.ktsbSpecialistOpinionWin = null;
    },
    
    issueOpinionWin_Itemclick:function(obj, record, item, index, e, eOpts){//专家意见回复窗体-选择
    	var issueOpinionForm=Ext.getCmp('ktsbEditSpecialistOpinionWin_form');
        issueOpinionForm.getForm().reset();
        this.issueOpinionRecord=record;
        //issueOpinionForm.show();
        //issueOpinionForm.getForm().loadRecord(record);
        Ext.getCmp('ktsbEditSpecialistOpinionWin_opinionId').setValue(record.data.id);
        Ext.getCmp('ktsbEditSpecialistOpinionWin_issueId').setValue(record.data.issueId);
        Ext.getCmp('ktsbEditSpecialistOpinionWin_issueStatus').setValue(record.data.issueStatus);
        Ext.getCmp('ktsbEditSpecialistOpinionWin_peopleId').setValue(record.data.peopleId);
        Ext.getCmp('ktsbEditSpecialistOpinionWin_name').setValue(record.data.name);
        
        
        /* Ext.Ajax.request({
            url: 'issueOpinion/findIssueOpinionById.action',
            params: {
				id:record.data.id	            
            },
            success: function (response){
            	var dataRecord = response.responseText;
            },
            scope: this
        });*/
       Ext.Ajax.request({
	            url: 'ktsb/findOpinionReplay.action?t='+new Date().getTime(),
	            actionMethods:{
					read:'POST'        
		        },
		        params: {
					opinionId:record.data.id,
					issueId:record.data.issueId,
					peopleId:record.data.peopleId,
					issueStatus:record.data.issueStatus
	            },
	            success: function (response){
	            	var opinion = response.responseText;
	            	if(opinion!=undefined){
	            		var jsonResult=Ext.decode(opinion);//opinion.opinionReplay.
	            		if(jsonResult.opinionReplay!=null){
	            			var opinionReplay= Ext.create('App.model.opinion.opinionReplayModel', jsonResult.opinionReplay); 
	        	  			issueOpinionForm.getForm().loadRecord(opinionReplay);
	            		}
	        	  		/*Ext.getCmp('opinionForm_issueXsJbxx').setValue(jsonResult.opinionReplay.issueXsJbxx);//1
	        	  		Ext.getCmp('opinionForm_issueXsCydwRy').setValue(jsonResult.opinionReplay.issueXsCydwRy);//2
	        	  		Ext.getCmp('opinionForm_issueXsJfsc').setValue(jsonResult.opinionReplay.issueXsJfsc);//3
	        	  		Ext.getCmp('opinionForm_issueXsRwnrKhzb').setValue(jsonResult.opinionReplay.issueXsRwnrKhzb);//4
	        	  		Ext.getCmp('opinionForm_issueXsQt').setValue(jsonResult.opinionReplay.issueXsQt);//5
	        	  		Ext.getCmp('opinionForm_issueWpYjhz').setValue(jsonResult.opinionReplay.issueWpYjhz);//6
	        	  		Ext.getCmp('opinionForm_issueHyscYj').setValue(jsonResult.opinionReplay.issueHyscYj);//7
	        	  		Ext.getCmp('opinionForm_issueFsXgws').setValue(jsonResult.opinionReplay.issueFsXgws);//8
	        	  		Ext.getCmp('opinionForm_issueFsFsyj').setValue(jsonResult.opinionReplay.issueFsFsyj);//9
	        	  		Ext.getCmp('ktsbEditSpecialistOpinionWin_id').setValue(jsonResult.opinionReplay.id);//id*/
	            	}
	            	
	            },
	            scope: this
	        });
        
        
        
        
        
        var fieldset_issueXsJbxx=Ext.getCmp('issueXsJbxx_fieldset'); //1
        var opinionWin_issueXsJbxx=Ext.getCmp('opinionWin_issueXsJbxx');
        if(record.data.issueXsJbxx!=''){
        	fieldset_issueXsJbxx.show();
        	opinionWin_issueXsJbxx.setValue(record.data.issueXsJbxx);
        }else{
        	fieldset_issueXsJbxx.hide();
        }
        
        
        var fieldset_issueXsCydwRy=Ext.getCmp('issueXsCydwRy_fieldset');//2
        var opinionWin_issueXsCydwRy=Ext.getCmp('opinionWin_issueXsCydwRy');
        if(record.data.issueXsCydwRy!=''){
        	fieldset_issueXsCydwRy.show();
        	opinionWin_issueXsCydwRy.setValue(record.data.issueXsCydwRy);
        }else{
        	opinionWin_issueXsCydwRy.setValue('');
        	fieldset_issueXsCydwRy.hide();	
        }
        
        
        var fieldset_issueXsJfsc=Ext.getCmp('issueXsJfsc_fieldset');//3
        var opinionWin_issueXsJfsc=Ext.getCmp('opinionWin_issueXsJfsc');
        if(record.data.issueXsJfsc!=''){
        	fieldset_issueXsJfsc.show();
        	opinionWin_issueXsJfsc.setValue(record.data.issueXsJfsc);
        }else{
        	fieldset_issueXsJfsc.hide();	
        	opinionWin_issueXsJfsc.setValue('');
        }
        
        
        var fieldset_issueXsRwnrKhzb=Ext.getCmp('issueXsRwnrKhzb_fieldset');//4
        var opinionWin_issueXsRwnrKhzb=Ext.getCmp('opinionWin_issueXsRwnrKhzb');
        if(record.data.issueXsRwnrKhzb!=''){
        	fieldset_issueXsRwnrKhzb.show();
        	opinionWin_issueXsRwnrKhzb.setValue(record.data.issueXsRwnrKhzb);
        }else{
        	opinionWin_issueXsRwnrKhzb.setValue('');
        	fieldset_issueXsRwnrKhzb.hide();	
        }
        
        
        var fieldset_issueXsQt=Ext.getCmp('issueXsQt_fieldset');//5
        var opinionWin_issueXsQt=Ext.getCmp('opinionWin_issueXsQt');
        if(record.data.issueXsQt!=''){
        	fieldset_issueXsQt.show();	
        	opinionWin_issueXsQt.setValue(record.data.issueXsQt);
        }else{
        	opinionWin_issueXsQt.setValue('');
        	fieldset_issueXsQt.hide();	
        }
        
        
        var fieldset_issueWpYjhz=Ext.getCmp('issueWpYjhz_fieldset');//6
        var opinionWin_issueWpYjhz=Ext.getCmp('opinionWin_issueWpYjhz');
        if(record.data.issueWpYjhz!=''){
        	fieldset_issueWpYjhz.show();	
        	opinionWin_issueWpYjhz.setValue(record.data.issueWpYjhz);
        }else{
        	opinionWin_issueWpYjhz.setValue('');
        	fieldset_issueWpYjhz.hide();	
        }
        
        
        var fieldset_issueHyscYj=Ext.getCmp('issueHyscYj_fieldset');//7
        var opinionWin_issueHyscYj=Ext.getCmp('opinionWin_issueHyscYj');
        if(record.data.issueHyscYj!=''){
        	fieldset_issueHyscYj.show();
        	opinionWin_issueHyscYj.setValue(record.data.issueHyscYj);
        }else{
        	opinionWin_issueHyscYj.setValue('');
        	fieldset_issueHyscYj.hide();	
        }
        
        
        var fieldset_issueFsXgws=Ext.getCmp('issueFsXgws_fieldset');//8
        var opinionWin_issueFsXgws=Ext.getCmp('opinionWin_issueFsXgws');
        if(record.data.issueFsXgws!=''){
        	fieldset_issueFsXgws.show();	
        	opinionWin_issueFsXgws.setValue(record.data.issueFsXgws);
        }else{
        	opinionWin_issueFsXgws.setValue('');
        	fieldset_issueFsXgws.hide();
        }
        
        
        var fieldset_issueFsFsyj=Ext.getCmp('issueFsFsyj_fieldset');//9
        var opinionWin_issueFsFsyj=Ext.getCmp('opinionWin_issueFsFsyj');
        if(record.data.issueFsFsyj!=''){
        	fieldset_issueFsFsyj.show();	
        	opinionWin_issueFsFsyj.setValue(record.data.issueFsFsyj);
        }else{
        	opinionWin_issueFsFsyj.setValue('');
        	fieldset_issueFsFsyj.hide();
        }
        
       

	},
/*****end专家意见回复****/
   

   
    ktlistZcdwEditEvent: function() {
        Ext.Msg.alert('Infomation','课题上报->承担单位编辑事件');
    },
    

    
    
    /**材料上报-提交按钮**/
    ktsbBigFormSubmitEvent:function(){
    	
    	if(this.ktsbId == undefined){
    		
    		Ext.Msg.alert('Infomation','请为材料指定一个课题再进行提交');
    		return ;
    	}
    	Ext.Ajax.request({
    		url:'ktsb/save.action?t='+new Date().getTime(),
    		method:'POST',
			params:{
				issueId:this.ktsbId
			},
    		success:function(response,options){
    			 Ext.Msg.alert('Infomation','课题材料提交成功！');
    		},
    		failure:function(response,options){
    			 Ext.Msg.alert('Infomation','课题材料提交失败！');
    		}
    	});
    },
    /**
     * 材料上报-责任人-添加行政责任人
     */
    ktsb_People_addEvent:function(){
    	if (this.ktsbAddPeople == null || this.ktsbAddPeople == undefined) {
            this.ktsbAddPeople = Ext.create('App.view.ktsb.ktsbAddXzPeopleWin');
        }
       this.ktsbAddPeople.addPeopleFlag = "AddAdminPeople";
       this.ktsbAddPeople.show();
    },
    /**
     * 材料上报-负责人-添加技术负责人
     */
    ktsb_SkillPeople_addEvent:function(){
    	
    	if (this.ktsbAddPeople == null || this.ktsbAddPeople == undefined) {
            this.ktsbAddPeople = Ext.create('App.view.ktsb.ktsbAddTechPeopleWin');
        }
        this.ktsbAddPeople.setTitle("添加技术负责人");
        this.ktsbAddPeople.addPeopleFlag = "AddSkillPeople";
        this.ktsbAddPeople.show();
    },
    /**
     * 材料上报-责任人-删除行政责任人
     */
    ktsb_People_delEvent:function(){
    	
    	var grid = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbPeopleGrid]')[0];
    	var rowRecord = grid.getSelectionModel().selected.items[0];
    	if(rowRecord == undefined){
    		Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
            return;
    	};
    	Ext.MessageBox.confirm('确认', '是否进行删除',
    	function(optional){
    		if(optional == 'yes'){
    			grid.getStore().remove(rowRecord);
    		}
    	});
    },
    /**
     * 材料上报-负责人-删除技术负责人
     */
    ktsb_SkillPeople_delEvent:function(){
    	
    	var grid = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbSkillPeopleGrid]')[0];
    	var rowRecord = grid.getSelectionModel().selected.items[0];
    	if(rowRecord == undefined){
    		Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
            return;
    	};
    	Ext.MessageBox.confirm('确认', '是否进行删除',
    	function(optional){
    		if(optional == 'yes'){
    			grid.getStore().remove(rowRecord);
    		}
    	});
    },
    ktsb_people_xz_zrr_addEvent:function(){
    	var mainpeopleFlag;
    	var addcurrentRecord;
    	var store;
    	var skill;
    	addcurrentRecord=this.ktsbAddPeople.down('form').getForm().getValues();
    	var currentRecord= Ext.create('App.model.people.peopleModel', addcurrentRecord);
    	if(this.ktsbAddPeople.addPeopleFlag =="AddAdminPeople"){
//    		var store = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbPeopleGrid]')[0].getStore();
    		var name=Ext.getCmp('ktsb_people_xz_zrr').lastValue;
    		currentRecord.data.name=name;
    		currentRecord.data.birthday=currentRecord.data.birthdayStr;
    		store = this.getStore('ktsb.ktsbPeopleStore');
    		skill = false;
    	}
    	if(this.ktsbAddPeople.addPeopleFlag =="AddSkillPeople"){
//    		var store = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbSkillPeopleGrid]')[0].getStore();
    		var name=Ext.getCmp('ktsb_people_tech_zrr').lastValue;
    		currentRecord.data.name=name;
    		currentRecord.data.birthday=currentRecord.data.birthdayStr;
    		var titletemp=Ext.getCmp('ktsbatptitle');
    		if(currentRecord.data.title==undefined){
    			var title=Ext.getCmp('ktsbatptitle').lastValue;
        		currentRecord.data.title=title;
    		}
    		if(currentRecord.data.degree==undefined){
    			var degree=Ext.getCmp('ktsbatpdegree').lastValue;
        		currentRecord.data.degree=degree;
    		}
    		if(currentRecord.data.idType==undefined){
    			var idType=Ext.getCmp('ktsbatpidtype').lastValue;
        		currentRecord.data.idType=idType;
    		}
    		store = this.getStore('ktsb.ktsbSkillPeopleStore');
    		skill = true;
    	}
    	if(this.ktsbAddPeople.addPeopleFlag =="AddMainPeople"){
    		var name=Ext.getCmp('ktsb_main_people').lastValue;
    		currentRecord.data.name=name;
    		if(currentRecord.data.title==undefined){
    			var title=Ext.getCmp('ktsbamptitle').lastValue;
        		currentRecord.data.title=title;
    		}
    		if(currentRecord.data.idType==undefined){
    			var idType=Ext.getCmp('ktsbampidtype').lastValue;
        		currentRecord.data.idType=idType;
    		}
    		store = this.getStore('ktsb.ktsbMainPeopleStore');
    		mainpeopleFlag = true;
    	}
    	if(currentRecord.data.name == null || currentRecord.data.name == undefined || currentRecord.data.name == ""){
    		return ;
    	}
    	var raw = true;
		for(var i=0; i<store.getCount();i++){
    		if(store.getAt(i).get('idpeople') == currentRecord.get('idpeople')){
    			if(store.getAt(i).get('name') == currentRecord.get('name')){
    				raw =false;
        			break;
    			}
    		}
    	}
    	if(raw){
    		if(skill){
    			this.getStore('ktsb.ktsbSkillPeopleStore').add(currentRecord);
    		}
    		if(!skill && !mainpeopleFlag)	{
    			this.getStore('ktsb.ktsbPeopleStore').add(currentRecord);
    		}
    		if(mainpeopleFlag){
    			this.getStore('ktsb.ktsbMainPeopleStore').add(currentRecord);
    		}
    		Ext.destroy(this.ktsbAddPeople);
    		this.ktsbAddPeople = null;
    	}else{
    		Ext.Msg.alert('Infomation','请勿重复添加该人员！');
    	}
    },
	
    ktsb_people_xz_zrr_closeEvent:function(){
    	Ext.destroy(this.ktsbAddPeople);
    	this.ktsbAddPeople = null;
    },
    ktsb_people_tech_zrr_closeEvent:function(){
    	Ext.destroy(this.ktsbAddPeople);
    	this.ktsbAddPeople = null;
    },
    ktsb_main_people_closeEvent:function(){
    	Ext.destroy(this.ktsbAddPeople);
    	this.ktsbAddPeople = null;
    },
    /**
     * 材料上报-添加行政责任人-选择人员触发 
     * @param {} field
     * @param {} newValue
     * @param {} oldValue
     * @param {} eOpts
     */
    ktsb_people_xz_zrrEvent:function(field, newValue, oldValue, eOpts){
		var rowRecord;
		var idStr = "ktsbaxzphideid,ktsbaxzpbirthday,ktsbaxzpcompany,ktsbaxzpduty,ktsbaxzpphone,ktsbaxzptelephone,ktsbaxzpfax,ktsbaxzpemail,ktsbaxzpsortno";
		var idArr = idStr.split(",")
		for(var m=0;m<idArr.length;m++){
			Ext.getCmp(idArr[m]).setValue('');
		}
		for(var i=0;i<Ext.getCmp('ktsb_people_xz_zrr').store.getCount();i++){
			if(Ext.getCmp('ktsb_people_xz_zrr').store.getAt(i).get('name')==newValue){
			rowRecord = Ext.getCmp('ktsb_people_xz_zrr').store.getAt(i);
			}
		}
		if(rowRecord){
		this.ktsbAddPeople.child('form').getForm().loadRecord(rowRecord);
		}
    },
    /**
     * 材料上报-添加技术责任人-选择人员触发 
     * @param {} field
     * @param {} newValue
     * @param {} oldValue
     * @param {} eOpts
     */
    ktsb_people_tech_zrrEvent:function(field, newValue, oldValue, eOpts){
		var rowRecord;
		var idStr = "ktsbatphideid,ktsbatpbirthdayStr,ktsbatptitle,ktsbatpdegree,ktsbatpspecialty,ktsbatpphone,ktsbatptelephone,ktsbatpfax,ktsbatpemail,ktsbatpidtype,ktsbatpidnumber,ktsbatpsortno";
		var idArr = idStr.split(",");
		Ext.getCmp('ktsbatpsex').reset();
		for(var m=0;m<idArr.length;m++){
			Ext.getCmp(idArr[m]).setValue('');
		}
		for(var i=0;i<Ext.getCmp('ktsb_people_tech_zrr').store.getCount();i++){
			if(Ext.getCmp('ktsb_people_tech_zrr').store.getAt(i).get('name')==newValue){
			rowRecord = Ext.getCmp('ktsb_people_tech_zrr').store.getAt(i);
			}
		}
		if(rowRecord){
		this.ktsbAddPeople.child('form').getForm().loadRecord(rowRecord);
		}
    },
    /**
     * 材料上报-添加主要人员-选择人员触发 
     * @param {} field
     * @param {} newValue
     * @param {} oldValue
     * @param {} eOpts
     */
    ktsb_main_people_event:function(field, newValue, oldValue, eOpts){
		var rowRecord;
		var idStr = "ktsbamphideid,ktsbampbirthday,ktsbamptitle,ktsbampspecialty,ktsbampdutytask,ktsbamptasktime,ktsbampcompany,ktsbampidtype,ktsbampidnumber,ktsbampsortno";
		var idArr = idStr.split(",")
		Ext.getCmp('ktsbampsex').reset();
		for(var m=0;m<idArr.length;m++){
			Ext.getCmp(idArr[m]).setValue('');
		}
		for(var i=0;i<Ext.getCmp('ktsb_main_people').store.getCount();i++){
			if(Ext.getCmp('ktsb_main_people').store.getAt(i).get('name')==newValue){
			rowRecord = Ext.getCmp('ktsb_main_people').store.getAt(i);
			}
		}
		if(rowRecord){
		this.ktsbAddPeople.child('form').getForm().loadRecord(rowRecord);
		}
    },
    
    
/*****材料上报-支持单位信息模块事件****/	
	
    ktsb_zcdw_addEvent: function() {//支持单位添加事件
       if(this.ktsbaddcompany == null || this.ktsbaddcompany == undefined) {
            this.ktsbaddcompany = Ext.create('App.view.ktsb.ktsbAddCompanyWin');
        }
       this.ktsbaddcompany.show();
    },
   
    ktlistZcdwDelEvent: function() {//支持单位删除事件
        Ext.Msg.alert('Infomation','课题上报->支持单位删除事件');
        var grid = Ext.ComponentQuery.query('ktsbMemberOrgForm gridpanel[itemId=ktsbCompanyListGrid]')[0];
    	var rowRecord = grid.getSelectionModel().selected.items[0];
    	if(rowRecord == undefined){
    		Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
            return;
    	};
    	Ext.MessageBox.confirm('确认', '是否进行删除',
    	function(optional){
    		if(optional == 'yes'){
    			grid.getStore().remove(rowRecord);
    		}
    	});
    },
    
    ktsb_company_addEvent:function(){
    	//var currentRecord = this.ktsbaddcompany.child('form').getForm().getRecord();
    	Ext.getCmp('ktsbAddCompanyWin_companyName').setValue(Ext.getCmp('ktsb_companyName_combobox').getValue());
    	var currentRecord= Ext.create('App.model.cddw.cddwModel', this.ktsbaddcompany.down('form').getForm().getValues()); 
    	var store;
    	var raw = true;
    	if(currentRecord == null || currentRecord == undefined){
    		return ;
    	}
    	store = this.getStore('ktsb.ktsbdwlistStore');
    	for(var i=0; i<store.getCount();i++){
    		if(store.getAt(i).get('companyName') == currentRecord.get('companyName')){
    			raw =false;
    			break;
    		}
    	}
    	if(raw){
    		store.add(currentRecord);
    		this.ktsb_company_closeEvent();
    	}else{
    		Ext.Msg.alert('Infomation','请勿重复添加该单位！');
    	}
    	
    },
   
    ktsb_company_closeEvent:function(){//材料上报-支持单位-添加窗体-删除
    	this.ktsbaddcompany.down('form').getForm().reset();
    	Ext.destroy(this.ktsbaddcompany);
    	this.ktsbaddcompany = null;
    },
    
    ktsb_companyName_comboboxEvent:function(field, newValue, oldValue, eOpts){//选择单位名称
    	
		var rowRecord;
		var store = Ext.getCmp('ktsb_companyName_combobox').getStore();
		for(var i=0;i<store.getCount();i++){
			if(store.getAt(i).get('companyName')==newValue){
			rowRecord = store.getAt(i);
			}
		}
		if(rowRecord){
			var city=Ext.getCmp('ktsbAddCompanyWin_belongAreaCity');
	    	var district = Ext.getCmp("ktsbAddCompanyWin_belongAreaDistrict");
	    	city.clearValue();
	    	district.clearValue();
	    	city.store.load({params:{id:rowRecord.data.belongAreaProvince}});
	    	district.store.load({params:{id:rowRecord.data.belongAreaCity}});
			this.ktsbaddcompany.child('form').getForm().loadRecord(rowRecord);
		}
    },
    
   
    select_AddCompanyWin_belongAreaProvince:function(combo, record,index){
    	var city=Ext.getCmp('ktsbAddCompanyWin_belongAreaCity');
	    var district = Ext.getCmp("ktsbAddCompanyWin_belongAreaDistrict");
	    city.clearValue();
	    district.clearValue();
	    city.store.load({params:{id:record[0].data.id}});
    },
    
    select_AddCompanyWin_belongAreaCity:function(combo, record,index){
    	var district = Ext.getCmp("ktsbAddCompanyWin_belongAreaDistrict");
	    district.clearValue();
	    district.store.load({params:{id:record[0].data.id}});
    },
    
 /*****材料上报-总体目标及指标(年度任务)*****/	
   ktsb_tasktarget_addEvent:function(){
   	 if(this.ktsbaddTaskTarget == null || this.ktsbaddTaskTarget == undefined) {
            this.ktsbaddTaskTarget = Ext.create('App.view.ktsb.ktsbAddTaskTargetWin');
      }
     this.ktsbaddTaskTarget.show();
   },
   ktsb_tasktarget_editEvent:function(){
   	var grid = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxTaskTargetGrid]')[0];
    var gridrowRecord = grid.getSelectionModel().selected.items[0];
    if(gridrowRecord){
    	 if(this.ktsbaddTaskTarget == null || this.ktsbaddTaskTarget == undefined) {
            this.ktsbaddTaskTarget = Ext.create('App.view.ktsb.ktsbAddTaskTargetWin');
      }
     this.ktsbaddTaskTarget.show();
		this.ktsbaddTaskTarget.child('form').getForm().loadRecord(gridrowRecord);
	}else{
		Ext.Msg.alert('Infomation','请选择一条记录进行编辑！');
		return;
	}
   },
   ktsb_tasktarget_delEvent:function(){
   	var grid = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxTaskTargetGrid]')[0];
    var gridrowRecord = grid.getSelectionModel().selected.items[0];
    	if(gridrowRecord == undefined){
    		Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
            return;
    	};
    	Ext.MessageBox.confirm('确认', '是否进行删除',
    	function(optional){
    		if(optional == 'yes'){
    			grid.getStore().remove(gridrowRecord);
    		}
    	});
   },
   ktsb_tasktarget_addWinEvent:function(){
   	
   	var rowRecord = this.ktsbaddTaskTarget.child('form').getForm().getValues();
    var store = this.getStore('ktsb.ktxxTaskTargetStore');
    var grid = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxTaskTargetGrid]')[0];
    var gridrowRecord = grid.getSelectionModel().selected.items[0];
//    store.sync();
//   	store.load();
     if(gridrowRecord){	
     	if(gridrowRecord.get('id') == rowRecord.id){//when edit
     		gridrowRecord.set('yearPlan',rowRecord.yearPlan);
     		gridrowRecord.set('quraterPlan',rowRecord.quraterPlan);
     		gridrowRecord.set('sortNo',rowRecord.sortNo);
     		gridrowRecord.set('task',rowRecord.task);
     		gridrowRecord.set('kpi',rowRecord.kpi);
     	}else{
     		 store.add(rowRecord);
     	}
     }else{
     	store.add(rowRecord);
     }
   	 if(this.ktsbaddTaskTarget != null || this.ktsbaddTaskTarget != undefined) {
   	 Ext.destroy(this.ktsbaddTaskTarget);
     this.ktsbaddTaskTarget = null;
   	 }
   },
    ktsb_tasktarget_closeWinEvent:function(){
   	Ext.destroy(this.ktsbaddTaskTarget);
    this.ktsbaddTaskTarget = null;
   },
  /**************************************************材料上报-总体目标及指标(工程配套条件)*************************************/	
    ktsb_sfgc_addEvent:function(){
    	 if(this.ktsbAddSfgcWin == null || this.ktsbAddSfgcWin == undefined) {
            this.ktsbAddSfgcWin = Ext.create('App.view.ktsb.ktsbAddSfgcWin');
      }
     this.ktsbAddSfgcWin.show();
    },
    ktsb_sfgc_editEvent:function(){
    	
	   	var grid = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxsfgcGrid]')[0];
	    var gridrowRecord = grid.getSelectionModel().selected.items[0];
	    if(gridrowRecord){
	    	 if(this.ktsbAddSfgcWin == null || this.ktsbAddSfgcWin == undefined) {
	            this.ktsbAddSfgcWin = Ext.create('App.view.ktsb.ktsbAddSfgcWin');
	      }
	     this.ktsbAddSfgcWin.show();
			this.ktsbAddSfgcWin.child('form').getForm().loadRecord(gridrowRecord);
		}else{
			Ext.Msg.alert('Infomation','请选择一条记录进行编辑！');
			return;
		}
   
    },
    ktsb_sfgc_delEvent:function(){
    	
   	var grid = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxsfgcGrid]')[0];
    var gridrowRecord = grid.getSelectionModel().selected.items[0];
    	if(gridrowRecord == undefined){
    		Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
            return;
    	};
    	Ext.MessageBox.confirm('确认', '是否进行删除',
    	function(optional){
    		if(optional == 'yes'){
    			grid.getStore().remove(gridrowRecord);
    		}
    	});
   
    },
    ktsb_sfgc_addWinEvent:function(){
    	var rowRecord = this.ktsbAddSfgcWin.child('form').getForm().getValues();
	    var store = this.getStore('ktsb.ktxxSfgcStore');
	    var grid = Ext.ComponentQuery.query('ktsbObjAndKpiForm gridpanel[itemId=ktxxsfgcGrid]')[0];
	    var gridrowRecord = grid.getSelectionModel().selected.items[0];
	     if(gridrowRecord){	
	     	if(gridrowRecord.get('id') == rowRecord.id){//when edit
	     		gridrowRecord.set('mainProject',rowRecord.mainProject);
	     		gridrowRecord.set('supportCondition',rowRecord.supportCondition);
	     		gridrowRecord.set('sortNo',rowRecord.sortNo);
	     		gridrowRecord.set('localOrg',rowRecord.localOrg);
	     	}else{
	     		 store.add(rowRecord);
	     	}
	     }else{
	     	store.add(rowRecord);
	     }
	   	 if(this.ktsbAddSfgcWin != null || this.ktsbAddSfgcWin != undefined) {
	   	 Ext.destroy(this.ktsbAddSfgcWin);
	     this.ktsbAddSfgcWin = null;
	   	 }
	   },
    ktsb_sfgc_closeWinEvent:function(){
    	Ext.destroy(this.ktsbAddSfgcWin);
   		this.ktsbAddSfgcWin = null;
    },
  /**************************************************材料上报-基础条件及优势(主要人员情况)*************************************/	
   ktsb_mainPeople_addEvent:function(){
   	
   		if (this.ktsbAddPeople == null || this.ktsbAddPeople == undefined) {
            this.ktsbAddPeople = Ext.create('App.view.ktsb.ktsbAddMainPeopleWin');
        }
        this.ktsbAddPeople.addPeopleFlag = "AddMainPeople";
        this.ktsbAddPeople.show();
   },
   ktsb_mainPeople_delEvent:function(){
   	
   		var grid = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel[itemId=ktsbCapabilityPeopleGrid]')[0];
    	var rowRecord = grid.getSelectionModel().selected.items[0];
    	if(rowRecord == undefined){
    		Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
            return;
    	};
    	Ext.MessageBox.confirm('确认', '是否进行删除',
    	function(optional){
    		if(optional == 'yes'){
    			grid.getStore().remove(rowRecord);
    		}
    	});
   },
   /************************************************begin 材料上报-基础条件及优势(目前承担其他课题情况)***********************************/	
   ktsb_qtkt_addEvent:function(){
	   if (this.qtktAddWin == null || this.qtktAddWin == undefined) {
           this.qtktAddWin = Ext.create('App.view.ktsb.ktsbAddOtherKtWin');
       }
       this.qtktAddWin.setTitle("添加其他课题信息");
       this.qtktAddWin.show();
       if(this.ktsbId == undefined) {
		   //Ext.MessageBox.alert("温馨提示", "请您先选择一行课题列表，再进行操作，谢谢！");
           //return;
       	}else{
       	 	Ext.getCmp('ktsbAddOtherKtWin_issueId').setValue(this.ktsbId);
       	}
   },
   
   ktsb_qtkt_add_execEvent : function () {
   	
	   	var  currentRecord= Ext.create('App.model.ktsb.ktsbIssuePlanModel', this.qtktAddWin.down('form').getForm().getValues()); 
		if(currentRecord == null || currentRecord == undefined){
			return ;
		}
		var store = this.getStore('ktsb.ktsbOtherKtStore');
		var raw = true;
		for(var i=0; i<store.getCount();i++){
			if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
				raw =false;
				break;
			}
		}
		if(raw){
			this.getStore('ktsb.ktsbOtherKtStore').add(currentRecord);
			this.ktsb_qtkt_add_cancelEvent();
	    	}else{
	    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
		}
   	
	/*   	if(this.ktsbId == undefined) {
	   		var  currentRecord= Ext.create('App.model.ktsb.ktsbIssuePlanModel', this.qtktAddWin.down('form').getForm().getValues()); 
	   		if(currentRecord == null || currentRecord == undefined){
	    		return ;
	    	}
	    	var store = this.getStore('ktsb.ktsbOtherKtStore');
	    	var raw = true;
	    	for(var i=0; i<store.getCount();i++){
	    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
	    			raw =false;
	    			break;
	    		}
	    	}
	    	if(raw){
	    		this.getStore('ktsb.ktsbOtherKtStore').add(currentRecord);
	    		this.ktsb_qtkt_add_cancelEvent();
		    	}else{
		    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
	    	}
	   	}else{
   			Ext.Ajax.request({
	        url: 'ktsb/addIssuePlan.action?t='+new Date().getTime(),
	        params: this.qtktAddWin.down('form').getForm().getValues(),
	        success: function (response){
		        	this.ktsb_qtkt_add_cancelEvent();
		        	this.storeQueryWithCondition();
		        },
		        scope: this
		    });
	   	}*/
   },
   
   ktsb_qtkt_add_cancelEvent : function () {
   	   this.qtktAddWin.down('form').getForm().reset();
       Ext.destroy(this.qtktAddWin);
       this.qtktAddWin = null;
   },
   
   
   ktsb_qtkt_editEvent: function() {
       var grid = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel')[1];
       var rowRecord = grid.getSelectionModel().selected.items[0];
       if(rowRecord == undefined) {
           Ext.MessageBox.alert("提示", "请选择一行，再进行编辑。");
           return;
       }
       if (this.qtktEditWin == null || this.qtktEditWin == undefined) {
           this.qtktEditWin = Ext.create('App.view.ktsb.ktsbEditOtherKtWin');
       }
       this.qtktEditWin.setTitle("修改其他课题信息");
       this.qtktEditWin.show();
       
       
       var editForm  = Ext.ComponentQuery.query('qtktEditWin form')[0];
       editForm.getForm().loadRecord(rowRecord);

       editForm.setDisabled(false);
       if(editForm.collapsed) {
           editForm.expand();
       }
   },
   
  
   
   ktsb_qtkt_edit_cancelEvent : function () {
   	   this.qtktEditWin.down('form').getForm().reset();
       Ext.destroy(this.qtktEditWin);
       this.qtktEditWin = null;
   },
   
   ktsb_qtkt_edit_execEvent : function () {
   	
   			var currentRecord= Ext.create('App.model.ktsb.ktsbIssuePlanModel', this.qtktEditWin.down('form').getForm().getValues()); 
	   		if(currentRecord == null || currentRecord == undefined){
	    		return ;
	    	}
	    	var store = this.getStore('ktsb.ktsbOtherKtStore');
	    	var raw = true;
	    	for(var i=0; i<store.getCount();i++){
	    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
	    			raw =false;
	    			break;
	    		}
	    	}
	    	if(raw){
	    		var grid = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel')[1];
      	 		var rowRecord = grid.getSelectionModel().selected.items[0];
	    		grid.getStore().remove(rowRecord);
	    		store.add(currentRecord);
	    		this.ktsb_qtkt_edit_cancelEvent();
		    	}else{
		    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
	    	}
   	
		/*if(this.ktsbId == undefined) {
	   		var currentRecord= Ext.create('App.model.ktsb.ktsbIssuePlanModel', this.qtktEditWin.down('form').getForm().getValues()); 
	   		if(currentRecord == null || currentRecord == undefined){
	    		return ;
	    	}
	    	var store = this.getStore('ktsb.ktsbOtherKtStore');
	    	var raw = true;
	    	for(var i=0; i<store.getCount();i++){
	    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
	    			raw =false;
	    			break;
	    		}
	    	}
	    	if(raw){
	    		var grid = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel')[1];
      	 		var rowRecord = grid.getSelectionModel().selected.items[0];
	    		grid.getStore().remove(rowRecord);
	    		store.add(currentRecord);
	    		this.ktsb_qtkt_edit_cancelEvent();
		    	}else{
		    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
	    	}
	   	}else{
	   	   Ext.Ajax.request({
	         url: 'ktsb/updateIssuePlan.action?t='+new Date().getTime(),
	         params: this.qtktEditWin.down('form').getForm().getValues(),
	         success: function (response){
		         	this.ktsb_qtkt_edit_cancelEvent();
		         	this.storeQueryWithCondition();
		         	Ext.MessageBox.alert("提示", "修改信息成功");
		         },
		         scope: this
		     });
	   	}*/
	  
	},
	
	ktsb_qtkt_delEvent:function(){
	   var grid = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel')[1];
       var rowRecord = grid.getSelectionModel().selected.items[0];
       if(rowRecord == undefined) {
           Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
           return;
       }
      Ext.MessageBox.confirm('确认', '是否进行删除',
        function (optional){
            if (optional == 'yes') {
            	grid.getStore().remove(rowRecord);
            	/*if(this.ktsbId == undefined){
            		grid.getStore().remove(rowRecord);
            	}else{
	            	   Ext.Ajax.request({
	                    url: 'ktsb/delIssuePlanById.action?t='+new Date().getTime(),
	                    params : {
	                        id:rowRecord.data.id
	                    },
	                    actionMethods:{
							read:'POST'        
				        },
				        reader: {
				            type: 'json'
				        },
	                    success:function(){ 
	                    	Ext.MessageBox.alert("提示", "删除信息成功");
	                    	this.storeQueryWithCondition();
	                    	},
	                    scope: this
	                });
            	
            	}*/
            }
        }, this);
	},

	
	storeQueryWithCondition : function () {
       var store = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel')[1];
       store.getSelectionModel().deselectAll();
       store.getStore().load({ params: {issueId:this.ktsbId}});
   },
   storeMainPeopleWithCondition : function(){//主要人员情况
   	
		var grid = Ext.ComponentQuery.query('ktsbCapabilityForm gridpanel')[0];
		grid.getSelectionModel().deselectAll();
		var store = grid.getStore();
		store.proxy.url = 'ktsb/mainpeoplelistall.action?issueId='+this.ktsbId;
		store.load();
   },
   /******************************end*********************************/	
	
	/****************begin 经费及任务分析(研究经费按单位分配)********************/
	ktsb_researchOutlay_addEvent:function(){
		this.ktsb_researchOutlay_show();
        this.researchOutlayWin.setTitle("添加研究经费按单位分配信息");
        this.researchOutlayWin.researchOutlayFlag="addResearchOutlay";
        if(this.ktsbId == undefined) {
		   //Ext.MessageBox.alert("温馨提示", "请您先选择一行课题列表，再进行操作，谢谢！");
           //return;
       	}else{
       		Ext.getCmp('editResearchOutlay_issueId').setValue(this.ktsbId);
       	}
	},
	
	
	
    ktsb_researchOutlay_win_execEvent:function(){
    	
    	var currentRecord= Ext.create('App.model.ktsb.ktsbResearchOutlayModel', this.researchOutlayWin.down('form').getForm().getValues()); 
   		if(currentRecord == null || currentRecord == undefined){
    		return ;
    	}
    	var store = this.getStore('ktsb.ktsbResearchOutlayStore');
    	var raw = true;
    	if(raw){
    		//debugger;
  	 		var boboxValue= Ext.getCmp('ktsb_researchOutla_combobox').rawValue;
  	 		currentRecord.set('orgName',boboxValue);
  	 		//var titleValue=this.researchOutlayWin.title;
  	 		if(this.researchOutlayWin.researchOutlayFlag=="editResearchOutlay"){
  	 			var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[1];
  	 			var rowRecord = grid.getSelectionModel().selected.items[0];
  	 			grid.getStore().remove(rowRecord);
  	 		}
  	 		store.add(currentRecord);
    		this.ktsb_researchOutlay_win_cancelEvent();
    	}else{
    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
		}
    	
       /*if(this.ktsbId == undefined) {
	   		var currentRecord= Ext.create('App.model.ktsb.ktsbResearchOutlayModel', this.researchOutlayWin.down('form').getForm().getValues()); 
	   		if(currentRecord == null || currentRecord == undefined){
	    		return ;
	    	}
	    	var store = this.getStore('ktsb.ktsbResearchOutlayStore');
	    	var raw = true;
	    	if(raw){
	    		//debugger;
      	 		var boboxValue= Ext.getCmp('ktsb_researchOutla_combobox').rawValue;
      	 		currentRecord.set('orgName',boboxValue);
      	 		//var titleValue=this.researchOutlayWin.title;
      	 		if(this.researchOutlayWin.researchOutlayFlag=="editResearchOutlay"){
      	 			var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[1];
      	 			var rowRecord = grid.getSelectionModel().selected.items[0];
      	 			grid.getStore().remove(rowRecord);
      	 		}
      	 		store.add(currentRecord);
	    		this.ktsb_researchOutlay_win_cancelEvent();
		    	}else{
		    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
	    	}
	   	}else{
		   	  Ext.Ajax.request({
	            url: 'ktsb/editResearchOutlay.action?t='+new Date().getTime(),
	            actionMethods:{
					read:'POST'        
		        },
	            params: this.researchOutlayWin.down('form').getForm().getValues(),
	            success: function (response){
	            	var text = response.responseText;
	            	this.ktsb_researchOutlay_win_cancelEvent();
	            	this.commonResearchOutlayCallback();
	            },
	            scope: this
	        });
	   	}*/
    },
    
   
    
    ktsb_researchOutlay_editEvent:function(){
       var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[1];
       var rowRecord = grid.getSelectionModel().selected.items[0];
       if(rowRecord == undefined) {
           Ext.MessageBox.alert("提示", "请选择一行，再进行修改。");
           return;
       }
    	this.ktsb_researchOutlay_show();
    	this.researchOutlayWin.setTitle("修改研究经费按单位分配信息");
    	this.researchOutlayWin.researchOutlayFlag="editResearchOutlay";
    	
    	var editResearchOutlayForm  = Ext.ComponentQuery.query('ktsbEditResearchOutlayWin form')[0];
        editResearchOutlayForm.getForm().loadRecord(rowRecord);
        editResearchOutlayForm.setDisabled(false);
        if(editResearchOutlayForm.collapsed) {
            editResearchOutlayForm.expand();
        }
    },
    
    ktsb_researchOutlay_delEvent:function(){
       var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[1];
       var rowRecord = grid.getSelectionModel().selected.items[0];
       if(rowRecord == undefined) {
           Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
           return;
       }
      Ext.MessageBox.confirm('确认', '是否进行删除',
        function (optional){
            if (optional == 'yes') {
            	grid.getStore().remove(rowRecord);
            	/*if(this.ktsbId == undefined){
            		grid.getStore().remove(rowRecord);
            	}else{
	            	Ext.Ajax.request({
	                    url: 'ktsb/delResearchOutlay.action?t='+new Date().getTime(),
	                    params : {
	                        id:rowRecord.data.id
	                    },
	                    actionMethods:{
							read:'POST'        
				        },
				        reader: {
				            type: 'json'
				        },
	                    success: function (response){
	            			var text = response.responseText;
	            			this.commonResearchOutlayCallback();
	            		},
	                    scope: this
	                });
            	}*/
            }
        }, this);
    },
    
    ktsb_researchOutlay_show:function(){
		if (this.researchOutlayWin == null || this.researchOutlayWin == undefined) {
           this.researchOutlayWin = Ext.create('App.view.ktsb.ktsbEditResearchOutlayWin');
       	}
       	this.researchOutlayWin.show();
	},
    
     ktsb_researchOutlay_win_cancelEvent:function(){
    	this.researchOutlayWin.down('form').getForm().reset();
        Ext.destroy(this.researchOutlayWin);
        this.researchOutlayWin = null;
    },
   
   commonResearchOutlayCallback : function (ctrl) {
       var store = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[1];
       store.getSelectionModel().deselectAll();
       // 取消选择的原因是当保存后，selectModel的备份数据已经与store的记录不同步
       // 此处也可以再次产生选择事件，或人为同步selectmodel与store的记录
       store.getStore().load({ params: {issueId:this.ktsbId}});
   },
   
  /*************************end********************************************/

	/*******************begin 材料上报-经费及任务分解(研究任务设置)**********************/	
   
	ktsb_research_task_addEvent:function(){
		   if(this.ktsbId == undefined) {
	 		  //Ext.MessageBox.alert("提示", "请选择一项课题，再进行添加。");
	 		  //return;
		   }
		   if (this.researchTaskAddWin == null || this.researchTaskAddWin == undefined) {
	          this.researchTaskAddWin = Ext.create('App.view.ktsb.ktsbAddResearchTaskWin');
	       }
	       this.researchTaskAddWin.setTitle("添加研究任务设置信息");
	       this.researchTaskAddWin.show();
	},
	
	ktsb_research_task_add_cancelEvent : function () {
	   	   this.researchTaskAddWin.down('form').getForm().reset();
           Ext.destroy(this.researchTaskAddWin);
     	   this.researchTaskAddWin = null;
	},
	
    ktsb_research_task_add_execEvent : function () {
    	
    	var currentRecord= Ext.create('App.model.ktsb.ktsbResearchTaskModel', this.researchTaskAddWin.down('form').getForm().getValues()); 
   		if(currentRecord == null || currentRecord == undefined){
    		return ;
    	}
    	var store = this.getStore('ktsb.ktsbResearchTaskStore');
    	var raw = true;
    	/*for(var i=0; i<store.getCount();i++){
    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
    			raw =false;
    			break;
    		}
    	}*/
    	if(raw){
    		var researchTaskAddWin_assumeOrgId_Value= Ext.getCmp('researchTaskAddWin_assumeOrgId').rawValue;
    		var researchTaskAddWin_joinOrgId_Value= Ext.getCmp('researchTaskAddWin_joinOrgId').rawValue;
  	 		currentRecord.set('assumeOrgName',researchTaskAddWin_assumeOrgId_Value);
    		currentRecord.set('joinOrgName',researchTaskAddWin_joinOrgId_Value);
    		
    		store.add(currentRecord);
    		this.ktsb_research_task_add_cancelEvent();
	    	}else{
	    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
    	}
    	
    	/*if(this.ktsbId == undefined) {
	   		var currentRecord= Ext.create('App.model.ktsb.ktsbResearchTaskModel', this.researchTaskAddWin.down('form').getForm().getValues()); 
	   		if(currentRecord == null || currentRecord == undefined){
	    		return ;
	    	}
	    	var store = this.getStore('ktsb.ktsbResearchTaskStore');
	    	var raw = true;
	    	for(var i=0; i<store.getCount();i++){
	    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
	    			raw =false;
	    			break;
	    		}
	    	}
	    	if(raw){
	    		var researchTaskAddWin_assumeOrgId_Value= Ext.getCmp('researchTaskAddWin_assumeOrgId').rawValue;
	    		var researchTaskAddWin_joinOrgId_Value= Ext.getCmp('researchTaskAddWin_joinOrgId').rawValue;
      	 		currentRecord.set('assumeOrgName',researchTaskAddWin_assumeOrgId_Value);
	    		currentRecord.set('joinOrgName',researchTaskAddWin_joinOrgId_Value);
	    		
	    		store.add(currentRecord);
	    		this.ktsb_research_task_add_cancelEvent();
		    	}else{
		    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
	    	}
	   	}else{
		   	 Ext.Ajax.request({
		        url: 'ktsb/rtadd.action?issueId='+this.ktsbId+'?t='+new Date().getTime(),
                actionMethods:{
					read:'POST'        
		        },
		        reader: {
		            type: 'json'
		        },
		        params: this.researchTaskAddWin.down('form').getForm().getValues(),
		        success: function (response){
		        	this.ktsb_research_task_add_cancelEvent();
		        	this.storeResearchTaskWithCondition();
		        },
		        scope: this
		    });
	   	}*/
	   
    },
    
	ktsb_research_task_delEvent:function(){
		 var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[0];
	       var rowRecord = grid.getSelectionModel().selected.items[0];
	       if(rowRecord == undefined) {
	           Ext.MessageBox.alert("提示", "请选择一行，再进行删除。");
	           return;
	       }
	       
	      Ext.MessageBox.confirm('确认', '是否进行删除',
	        function (optional){
		            if (optional == 'yes') {
		            	grid.getStore().remove(rowRecord);
		            	
		            	/*if(this.ktsbId == undefined){
	            		grid.getStore().remove(rowRecord);
	            		}else{
		            	 	Ext.Ajax.request({
			                    url: 'ktsb/rtdel.action?t='+new Date().getTime(),
			                    params : {
			                        id:rowRecord.data.id
			                    },
			                    actionMethods:{
									read:'POST'        
						        },
						        reader: {
						            type: 'json'
						        },
			                    success: function (response){
						        	this.storeResearchTaskWithCondition();
						        }, 
			                    scope: this
			                });
	            		}*/
	            }
	        }, this);
		},
    
    ktsb_research_task_editEvent:function(){
    	var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[0];
        var rowRecord = grid.getSelectionModel().selected.items[0];
        if(rowRecord == undefined) {
            Ext.MessageBox.alert("提示", "请选择一行，再进行编辑。");
            return;
        }
        
        if (this.researchTaskEditWin == null || this.researchTaskEditWin == undefined) {
            this.researchTaskEditWin = Ext.create('App.view.ktsb.ktsbEditResearchTaskWin');
        }
        this.researchTaskEditWin.setTitle("编辑研究任务设置信息");
        this.researchTaskEditWin.show();
        
        var editForm  = Ext.ComponentQuery.query('researchTaskEditWin form')[0];
        editForm.getForm().loadRecord(rowRecord);
	},
	
	ktsb_research_task_edit_cancelEvent : function () {
	   	   this.researchTaskEditWin.down('form').getForm().reset();
           Ext.destroy(this.researchTaskEditWin);
     	   this.researchTaskEditWin = null;
	},
	
	ktsb_research_task_edit_execEvent : function () {
		
		var currentRecord= Ext.create('App.model.ktsb.ktsbResearchTaskModel', this.researchTaskEditWin.down('form').getForm().getValues()); 
   		if(currentRecord == null || currentRecord == undefined){
    		return ;
    	}
    	var store = this.getStore('ktsb.ktsbResearchTaskStore');
    	var raw = true;
    	/*for(var i=0; i<store.getCount();i++){
    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
    			raw =false;
    			break;
    		}
    	}*/
    	if(raw){
    		var researchTaskEditWin_assumeOrgId_Value= Ext.getCmp('researchTaskEditWin_assumeOrgId').rawValue;
    		var researchTaskEditWin_joinOrgId_Value= Ext.getCmp('researchTaskEditWin_joinOrgId').rawValue;
  	 		currentRecord.set('assumeOrgName',researchTaskEditWin_assumeOrgId_Value);
    		currentRecord.set('joinOrgName',researchTaskEditWin_joinOrgId_Value);
    		
    		var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[0];
  	 		var rowRecord = grid.getSelectionModel().selected.items[0];
    		grid.getStore().remove(rowRecord);
    		store.add(currentRecord);
    		this.ktsb_research_task_edit_cancelEvent();
	    	}else{
	    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
    	}
		
		
		
		
		/*if(this.ktsbId == undefined) {
	   		var currentRecord= Ext.create('App.model.ktsb.ktsbResearchTaskModel', this.researchTaskEditWin.down('form').getForm().getValues()); 
	   		if(currentRecord == null || currentRecord == undefined){
	    		return ;
	    	}
	    	var store = this.getStore('ktsb.ktsbResearchTaskStore');
	    	var raw = true;
	    	for(var i=0; i<store.getCount();i++){
	    		if(store.getAt(i).get('issueName') == currentRecord.get('issueName')){
	    			raw =false;
	    			break;
	    		}
	    	}
	    	if(raw){
	    		var researchTaskEditWin_assumeOrgId_Value= Ext.getCmp('researchTaskEditWin_assumeOrgId').rawValue;
	    		var researchTaskEditWin_joinOrgId_Value= Ext.getCmp('researchTaskEditWin_joinOrgId').rawValue;
      	 		currentRecord.set('assumeOrgName',researchTaskEditWin_assumeOrgId_Value);
	    		currentRecord.set('joinOrgName',researchTaskEditWin_joinOrgId_Value);
	    		
	    		var grid = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[0];
      	 		var rowRecord = grid.getSelectionModel().selected.items[0];
	    		grid.getStore().remove(rowRecord);
	    		store.add(currentRecord);
	    		this.ktsb_research_task_edit_cancelEvent();
		    	}else{
		    		Ext.Msg.alert('Infomation','请勿重复添加该姓名！');
	    	}
	   	}else{
		   	 Ext.Ajax.request({
			        url:'ktsb/rtupdate.action?t='+new Date().getTime(),
    				method:'POST',
    				params:{
    					issueId:this.ktsbId
    				},
			        params: this.researchTaskEditWin.down('form').getForm().getValues(),
			        success: function (response){
			        	this.ktsb_research_task_edit_cancelEvent();
			        	this.storeResearchTaskWithCondition();
			        },
			        scope: this
			    });
	   	}*/
		
		   
	},
	storeDirectorWithCondition : function(){ //行政责任人编辑时加载
		var grid = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbPeopleGrid]')[0];
		grid.getSelectionModel().deselectAll();
		var store = grid.getStore();
		store.proxy.url = 'ktsb/directorlistall.action?t='+new Date().getTime(),
		store.load({ params: {issueId:this.ktsbId}});
	},
	storeTechmemberWithCondition : function(){//技术责任人加载
		var grid = Ext.ComponentQuery.query('ktsbPeopleInchargeForm gridpanel[itemId=ktsbSkillPeopleGrid]')[0];
		grid.getSelectionModel().deselectAll();
		var store = grid.getStore();
		store.proxy.url = 'ktsb/techmemberlistall.action?issueId='+this.ktsbId;
		store.load();
	},
	 storeCompanyWithCondition : function(){
    	var grid = Ext.ComponentQuery.query('ktsbMemberOrgForm gridpanel[itemId=ktsbCompanyListGrid]')[0];
    	grid.getSelectionModel().deselectAll();
		var store = grid.getStore();
		store.proxy.url = 'ktsb/companylistall.action?issueId='+this.ktsbId;
		store.load();
    },
	storeResearchTaskWithCondition : function () {
       var store = Ext.ComponentQuery.query('ktsbTaskBreakdownForm gridpanel')[0];
       store.getSelectionModel().deselectAll();
       store.getStore().load({ params: {issueId:this.ktsbId}});
    },
   
    /*************************end********************************************/
    /************************经费预算 start**********************************/
    budgetStoreload :function(){
    	var store = this.getStore('ktsb.ktsbFormBudgetStore');
    	if(this.ktsbId == undefined){
    		store.proxy = new Ext.data.HttpProxy({url:'app/store/ktsb/budget.json'});
    		sotre.load();
    	}else{
    		store.proxy.url='ktxx/getBudgets1.action?issueId='+this.ktsbId;  
    		store.load();
    	}
    }
   /************************经费预算 end**********************************/ 
});
