DROP TABLE jinhuo_table;
CREATE TABLE jinhuo_table ( jinhuo_id bigint NOT NULL, danhao_id varchar(16), jinhuoriqi date, kuanhao_id varchar(12) NOT NULL, yanse varchar(8) NOT NULL, chima varchar(8) NOT NULL, shuliang int DEFAULT '0', jinjia float DEFAULT '0', chengbenjia float DEFAULT '0', shoujia float DEFAULT '0', zhuangtai char(1) DEFAULT '0', delflg char(1) DEFAULT '0', beizhu varchar(100), PRIMARY KEY (jinhuo_id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP INDEX ix1 ON jinhuo_table;
CREATE UNIQUE INDEX ix1 ON jinhuo_table (jinhuo_id);
DROP INDEX ix2 ON jinhuo_table;
CREATE INDEX ix2 ON jinhuo_table (kuanhao_id, yanse, chima);
DROP INDEX ix3 ON jinhuo_table;
CREATE INDEX ix3 ON jinhuo_table (danhao_id);
DROP TABLE kehu_table;
CREATE TABLE kehu_table ( kehu_id int NOT NULL, kehuname varchar(30) NOT NULL, kehusex char(1) DEFAULT '0', age int, biecheng varchar(30), dianming varchar(50), phone1 varchar(20), phone2 varchar(20), address1 varchar(100), address2 varchar(100), level int DEFAULT '1', infor1 varchar(50), infor2 varchar(50), infor3 varchar(50), infor4 varchar(50), zuqun_id int, zhuangtai char(1) DEFAULT '0', zhuceriqi date, qq varchar(20), weixin varchar(20), taobao varchar(200), beizhu varchar(100), PRIMARY KEY (kehu_id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into kehu_table (kehu_id, kehuname, kehusex, age, biecheng, dianming, phone1, phone2, address1, address2, level, infor1, infor2, infor3, infor4, zuqun_id, zhuangtai, zhuceriqi, qq, weixin, taobao, beizhu) values (100, '匿名', '0', 99, '默认客户', '虚拟店名', '9999', '9999', '虚拟地址', '虚拟地址', 1, null, null, null, null, 1, '0', null, '999999', null, null, '虚拟客户');
DROP INDEX ix1 ON kehu_table;
CREATE UNIQUE INDEX ix1 ON kehu_table (kehu_id);
DROP INDEX ix8 ON kehu_table;
CREATE UNIQUE INDEX ix8 ON kehu_table (dianming);
DROP INDEX ix2 ON kehu_table;
CREATE INDEX ix2 ON kehu_table (kehuname);
DROP INDEX ix3 ON kehu_table;
CREATE INDEX ix3 ON kehu_table (biecheng);
DROP INDEX ix4 ON kehu_table;
CREATE INDEX ix4 ON kehu_table (zuqun_id);
DROP INDEX ix5 ON kehu_table;
CREATE INDEX ix5 ON kehu_table (qq);
DROP INDEX ix6 ON kehu_table;
CREATE INDEX ix6 ON kehu_table (weixin);
DROP INDEX ix7 ON kehu_table;
CREATE INDEX ix7 ON kehu_table (taobao);
DROP TABLE kucun_table;
CREATE TABLE kucun_table ( kucun_id bigint DEFAULT '0' NOT NULL, kuanhao_id varchar(12) NOT NULL, yanse varchar(8) NOT NULL, chima varchar(8) NOT NULL, shuliang int DEFAULT '0', jinjia float DEFAULT '0', chengbenjia float DEFAULT '0', shoujia float DEFAULT '0', beizhu varchar(100), PRIMARY KEY (kucun_id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP INDEX ix1 ON kucun_table;
CREATE UNIQUE INDEX ix1 ON kucun_table (kucun_id);
DROP INDEX ix3 ON kucun_table;
CREATE UNIQUE INDEX ix3 ON kucun_table (kuanhao_id, yanse, chima);
DROP INDEX kucun_kuanhao_index ON kucun_table;
CREATE INDEX kucun_kuanhao_index ON kucun_table (kuanhao_id);
DROP TABLE xiaoshou_table;
CREATE TABLE xiaoshou_table ( xiaoshou_id bigint NOT NULL, kucun_id bigint NOT NULL, kuanhao_id varchar(12) NOT NULL, yanse varchar(8) NOT NULL, chima varchar(8) NOT NULL, shuliang int DEFAULT '0', shoujia float DEFAULT '0', shijishoukuan float DEFAULT '0', maijia_id int, maijiaxingming varchar(30), zhuangtai char(1) DEFAULT '0', delflg char(1) DEFAULT '0', beizhu varchar(100), PRIMARY KEY (xiaoshou_id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP INDEX ix1 ON xiaoshou_table;
CREATE UNIQUE INDEX ix1 ON xiaoshou_table (xiaoshou_id);
DROP INDEX ix2 ON xiaoshou_table;
CREATE INDEX ix2 ON xiaoshou_table (kucun_id);
DROP INDEX ix3 ON xiaoshou_table;
CREATE INDEX ix3 ON xiaoshou_table (kuanhao_id);
DROP INDEX ix4 ON xiaoshou_table;
CREATE INDEX ix4 ON xiaoshou_table (kuanhao_id, yanse, chima);
DROP INDEX ix5 ON xiaoshou_table;
CREATE INDEX ix5 ON xiaoshou_table (maijia_id);
DROP INDEX ix6 ON xiaoshou_table;
CREATE INDEX ix6 ON xiaoshou_table (maijiaxingming);
