/*
 * File: app/store/ktsb/ktsbdwlistStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.store.ktsb.ktsbdwlistStore', {
    extend: 'Ext.data.Store',

    requires: [
        'App.model.cddw.cddwModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
        	storeId:'ktsb.ktsbdwlistStore',
            autoLoad: false,
            model: 'App.model.cddw.cddwModel',
            proxy: {
                type: 'ajax',
//                url: 'app/data/ktsb/ktsb_zcdw_list.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});