/*
 * File: app/model/ktsb/ktsblistModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.model.ktsb.ktsblistModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'issueNo'
        },
        {
            name: 'issueName'
        },
        {
            name: 'projectName'
        },
        {
            name: 'topicName'
        },
        {
            name: 'belongvallery'
        },
        {
            name: 'principal'
        },
        {
            name: 'startTime'
        },
        {
            name: 'status'
        }
    ]
});